In [5]:
import csv
import pandas as pd
import ast
import lotus

# Common Utils

In [7]:
def read_csv(csv_file, index_col=-1):
    if index_col != -1:
        df = pd.read_csv(csv_file, index_col=index_col)
    else:
        df = pd.read_csv(csv_file)
    
    def parse_list_col(x):
        """
        Try to parse x (a string) as a Python list using literal_eval.
        If parsing fails, return x unchanged.
        """
        if isinstance(x, str):
            try:
                return ast.literal_eval(x)
            except (ValueError, SyntaxError):
                # If x is not a valid Python literal, just return x
                return x
        return x
    
    # Convert string -> list for the specified columns
    for col in ["pred_reaction", "reactions_list", "_map"]:
        if col in df.columns:
            df[col] = df[col].apply(parse_list_col)
            
    return df

# Parse regular join output for rerank

In [3]:
# answers_df =  pd.read_csv("biodex_cascade_answers_for_lm_rerank.csv", index_col=0)
answers_df = read_csv("biodex_cascade_answers_for_lm_rerank.csv", index_col=0)

In [4]:
answers_df['reactions_list'].iloc[0]

['Heparin-induced thrombocytopenia']

In [5]:
def to_comma_separated(val):
    """
    Safely convert val (which could be a list or a string representing a list)
    into a comma-separated string.
    """
    if isinstance(val, list):
        # Already a list of strings
        return ", ".join(val)
    elif isinstance(val, str):
        # Possibly a string like "['foo', 'bar']"
        # Try literal_eval to see if it's a valid Python list
        try:
            parsed = ast.literal_eval(val)
            if isinstance(parsed, list):
                # It's a real list, convert to comma-separated
                return ", ".join(parsed)
            else:
                # Not a list—just return the original string
                return val
        except (SyntaxError, ValueError):
            # It's not a parseable list, return as is
            return val
    else:
        # Fallback: convert whatever it is to string
        return str(val)

# 2) Normalize reactions_list so every row is a comma-separated string
answers_df["reactions_list"] = answers_df["reactions_list"].apply(to_comma_separated)

# 3) Group by and aggregate
grouped_df = (
    answers_df
    .groupby(["title", "abstract", "reactions", "reactions_list", "patient_description"], dropna=False)
    .apply(lambda grp: grp["reaction"].tolist())
    .reset_index(name="pred_reaction")
)

# 4) Convert that comma-separated string (in grouped_df) back to a list
grouped_df["reactions_list"] = grouped_df["reactions_list"].apply(
    lambda s: s.split(", ")
)

/tmp/user/24031/ipykernel_3413155/2824786360.py:34: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda grp: grp["reaction"].tolist())

In [6]:
grouped_df

,title,abstract,reactions,reactions_list,patient_description,pred_reaction
0,A Case Report of Acute Transient Encephalopath...,Methemoglobinemia is caused due to an increase...,"Facial paralysis, Methaemoglobinaemia","[Facial paralysis, Methaemoglobinaemia]",TITLE:\nA Case Report of Acute Transient Encep...,"[Cyanosis, Methaemoglobinaemia, Cyanosis centr..."
1,A Case Report of COVID-Associated Catastrophic...,Antiphospholipid syndrome (APS) is an autoimmu...,"Haemoglobin decreased, Off label use, Retroper...","[Haemoglobin decreased, Off label use, Retrope...",TITLE:\nA Case Report of COVID-Associated Cata...,"[Autoimmune haemolytic anaemia, Autoimmune ana..."
2,A Case of Hemorrhagic Cholecystitis and Hemobi...,BACKGROUND Hemorrhagic cholecystitis is a rare...,"Cholecystitis acute, Haemobilia, Haemorrhagic ...","[Cholecystitis acute, Haemobilia, Haemorrhagic...",TITLE:\nA Case of Hemorrhagic Cholecystitis an...,"[Haemorrhagic cholecystitis, Haemobilia, Cysti..."
3,A Case of Non-small Cell Lung Cancer Treated w...,The echinoderm microtubule associated protein-...,"Decreased appetite, Disease progression, Dyspn...","[Decreased appetite, Disease progression, Dysp...",TITLE:\nA Case of Non-small Cell Lung Cancer T...,"[Transaminases abnormal, Hypertransaminasaemia..."
4,A Case of Paraneoplastic Pemphigus as a Preced...,"Paraneoplastic pemphigus is a rare, life-threa...","Bronchopulmonary aspergillosis, Obliterative b...","[Bronchopulmonary aspergillosis, Obliterative ...",TITLE:\nA Case of Paraneoplastic Pemphigus as ...,"[Bronchopulmonary aspergillosis, Obliterative ..."
...,...,...,...,...,...,...
220,Unusual Presentation of Relapsing Polychondrit...,BACKGROUND Relapsing polychondritis (RP) is an...,"Blood glucose abnormal, Spinal compression fra...","[Blood glucose abnormal, Spinal compression fr...",TITLE:\nUnusual Presentation of Relapsing Poly...,"[Steroid diabetes, Steroid therapy, Transamina..."
221,Vertebral artery dissection in term pregnancy ...,BACKGROUND\nVertebral artery dissection is an ...,"Condition aggravated, Exposure during pregnanc...","[Condition aggravated, Exposure during pregnan...",TITLE:\nVertebral artery dissection in term pr...,"[Dizziness, Vomiting, Nausea]"
222,Vertical transmission: evidence of COVID-19 in...,This article reports the case of a 28-year-old...,"COVID-19, Drug ineffective, Exposure during pr...","[COVID-19, Drug ineffective, Exposure during p...",TITLE:\nVertical transmission: evidence of COV...,"[Lymphocytopenia neonatal, Tachycardia foetal,..."
223,Very severe aplastic anemia in an 80-year-old ...,Although the patient with very severe aplastic...,"Pneumonia, Product use in unapproved indicatio...","[Pneumonia, Product use in unapproved indicati...",TITLE:\nVery severe aplastic anemia in an 80-y...,"[Serum sickness, Sepsis, Neutropenic sepsis, P..."
224,Vitiligo with Progressive Repigmentation durin...,The proposed role of interleukin (IL)-17 in vi...,"Drug ineffective, Paradoxical drug reaction, V...","[Drug ineffective, Paradoxical drug reaction, ...",TITLE:\nVitiligo with Progressive Repigmentati...,"[Vitiligo, Skin hypopigmentation, Pigmentation..."

In [8]:
top_k = 25
rerank_prompt = (
    f"Given {{patient_description}}, pick the {top_k} most applicable adverse drug reactions from the options "
    f"that are directly expressed in the following list: {{pred_reaction}}. "
    "Rank from most applicable to least applicable. "
    "Always write your answer as a list of comma-separated adverse drug reactions only and nothing else."
)

rerank_num_lm = grouped_df.shape[0]

grouped_df = grouped_df.sem_map(
    rerank_prompt
)

ValueError: The language model must be an instance of LM. Please configure a valid language model using lotus.settings.configure()

# Parse rerank output

In [71]:
# top_answer_df = pd.read_csv("biodex_reranked_answers.csv", index_col=0)
top_answer_df = read_csv("biodex_reranked_answers.csv", index_col=0)

In [72]:
top_answer_df

,title,abstract,reactions,reactions_list,patient_description,pred_reaction,_map
0,A Case Report of Acute Transient Encephalopath...,Methemoglobinemia is caused due to an increase...,"Facial paralysis, Methaemoglobinaemia","[Facial paralysis, Methaemoglobinaemia]",TITLE:\nA Case Report of Acute Transient Encep...,"[Cyanosis, Methaemoglobinaemia, Cyanosis centr...","Cyanosis, Methaemoglobinaemia, Hypoxia, Cyanos..."
1,A Case Report of COVID-Associated Catastrophic...,Antiphospholipid syndrome (APS) is an autoimmu...,"Haemoglobin decreased, Off label use, Retroper...","[Haemoglobin decreased, Off label use, Retrope...",TITLE:\nA Case Report of COVID-Associated Cata...,"[Autoimmune haemolytic anaemia, Autoimmune ana...","Thrombocytopenia, Haemolytic anaemia, Autoimmu..."
2,A Case of Hemorrhagic Cholecystitis and Hemobi...,BACKGROUND Hemorrhagic cholecystitis is a rare...,"Cholecystitis acute, Haemobilia, Haemorrhagic ...","[Cholecystitis acute, Haemobilia, Haemorrhagic...",TITLE:\nA Case of Hemorrhagic Cholecystitis an...,"[Haemorrhagic cholecystitis, Haemobilia, Cysti...","Haemorrhagic cholecystitis, Haemobilia, Haemor..."
3,A Case of Non-small Cell Lung Cancer Treated w...,The echinoderm microtubule associated protein-...,"Decreased appetite, Disease progression, Dyspn...","[Decreased appetite, Disease progression, Dysp...",TITLE:\nA Case of Non-small Cell Lung Cancer T...,"[Transaminases abnormal, Hypertransaminasaemia...","Transaminases abnormal, Hypertransaminasaemia,..."
4,A Case of Paraneoplastic Pemphigus as a Preced...,"Paraneoplastic pemphigus is a rare, life-threa...","Bronchopulmonary aspergillosis, Obliterative b...","[Bronchopulmonary aspergillosis, Obliterative ...",TITLE:\nA Case of Paraneoplastic Pemphigus as ...,"[Bronchopulmonary aspergillosis, Obliterative ...",Here is the list of 25 most applicable adverse...
...,...,...,...,...,...,...,...
220,Unusual Presentation of Relapsing Polychondrit...,BACKGROUND Relapsing polychondritis (RP) is an...,"Blood glucose abnormal, Spinal compression fra...","[Blood glucose abnormal, Spinal compression fr...",TITLE:\nUnusual Presentation of Relapsing Poly...,"[Steroid diabetes, Steroid therapy, Transamina...","Steroid diabetes, Steroid therapy, Transaminas..."
221,Vertebral artery dissection in term pregnancy ...,BACKGROUND\nVertebral artery dissection is an ...,"Condition aggravated, Exposure during pregnanc...","[Condition aggravated, Exposure during pregnan...",TITLE:\nVertebral artery dissection in term pr...,"[Dizziness, Vomiting, Nausea]","Dizziness, Vomiting, Nausea"
222,Vertical transmission: evidence of COVID-19 in...,This article reports the case of a 28-year-old...,"COVID-19, Drug ineffective, Exposure during pr...","[COVID-19, Drug ineffective, Exposure during p...",TITLE:\nVertical transmission: evidence of COV...,"[Lymphocytopenia neonatal, Tachycardia foetal,...","Foetal tachycardia, Tachycardia foetal, Neonat..."
223,Very severe aplastic anemia in an 80-year-old ...,Although the patient with very severe aplastic...,"Pneumonia, Product use in unapproved indicatio...","[Pneumonia, Product use in unapproved indicati...",TITLE:\nVery severe aplastic anemia in an 80-y...,"[Serum sickness, Sepsis, Neutropenic sepsis, P...",Here is the list of 25 most applicable adverse...
224,Vitiligo with Progressive Repigmentation durin...,The proposed role of interleukin (IL)-17 in vi...,"Drug ineffective, Paradoxical drug reaction, V...","[Drug ineffective, Paradoxical drug reaction, ...",TITLE:\nVitiligo with Progressive Repigmentati...,"[Vitiligo, Skin hypopigmentation, Pigmentation...","Vitiligo, Skin hypopigmentation, Pigmentation ..."

In [83]:
top_k = 25
known_prefixes = [
    f"Based on the patient description, the {top_k} most applicable adverse drug reactions are:\n\n",
    f"Based on the Patient_description, the {top_k} most applicable adverse drug reactions from the Combined_reaction_list are:\n\n",
    f"Based on the Patient_description, the {top_k} most applicable adverse drug reactions are:\n\n",
    f"Based on the provided Patient_description, the {top_k} most applicable adverse drug reactions from the Combined_reaction_list are:\n\n",
    f"Here is the list of {top_k} most applicable adverse drug reactions:\n\n",
    "Here is the answer:\n\n",
    f"Here is the list of the {top_k} most applicable adverse drug reactions:\n\n",
    f"Here is the list of {top_k} most applicable adverse drug reactions:\n\n",
    f"Here is the list of {top_k} most applicable adverse drug reactions from the options, ranked from most applicable to least applicable:"
]
def remove_known_prefixes(text: str, prefixes: list) -> str:
    """
    Removes the first matching prefix from 'text' if found in 'prefixes',
    otherwise returns text unchanged.
    """
    for prefix in prefixes:
        if text.startswith(prefix):
            return text[len(prefix):]
    return text

In [84]:
top_answer_df["_map"] = top_answer_df["_map"].fillna("").apply(
    lambda x: remove_known_prefixes(x, known_prefixes)
)

In [85]:
for i, row in top_answer_df.iterrows():
    # print(f"Question {i}:")
    print(row["_map"])

Cyanosis, Methaemoglobinaemia, Hypoxia, Cyanosis central, Cyanopsia, Dysglobulinaemia, Congenital methaemoglobinaemia, Hypochromasia
Thrombocytopenia, Haemolytic anaemia, Autoimmune haemolytic anaemia, Autoimmune anaemia, Thrombocytopenia, Platelet dysfunction, Renal impairment, Renal failure, Autoimmune pancytopenia, Renal haemorrhage, Thrombocytopenia, Haemolytic anaemia, Autoimmune haemolytic anaemia, Autoimmune anaemia, Platelet dysfunction, Renal impairment, Renal failure, Autoimmune pancytopenia, Renal haemorrhage, Thrombocytopenia, Haemolytic anaemia, Autoimmune haemolytic anaemia, Autoimmune anaemia, Platelet dysfunction, Renal impairment.
Haemorrhagic cholecystitis, Haemobilia, Haemorrhage, Gastrointestinal haemorrhage, Upper gastrointestinal haemorrhage, Gastric haemorrhage, Gastric ulcer haemorrhage, Haemorrhagic gastritis, Haemorrhagic cyst, Cholecystitis, Enterocolitis haemorrhagic, Rectal haemorrhage, Diarrhoea haemorrhagic, Haemorrhagic erosive gastritis, Gastrointestinal vascular malformation haemorrhagic, Oesophageal ulcer haemorrhage, Oesophageal haemorrhage, Duodenal ulcer haemorrhage, Haematochezia, Haemorrhagic ascites, Abdominal wall haemorrhage, Intra-abdominal haemorrhage, Cholecystocholangitis, Cholelithiasis, Haemorrhage prophylaxis
Transaminases abnormal, Hypertransaminasaemia, Gastrointestinal mucosa hyperaemia
Bronchiolitis obliterans, Pulmonary aspergillosis, Bronchitis fungal, Respiratory tract infection fungal, Pneumonia fungal, Aspergilloma, Bronchitis mycoplasmal, Pulmonary mucormycosis, Bronchitis pneumococcal, Pneumonia toxoplasmal, Sinusitis aspergillus, Acute pulmonary histoplasmosis, Meningitis aspergillus, Upper respiratory fungal infection, Oro-pharyngeal aspergillosis, Pulmonary granuloma, Alveolitis, Pneumonitis, Cerebral aspergillosis, Bronchial ulceration, Eosinophilic bronchitis, Pulmonary lymphangiectasia, Bronchostenosis, Alveolar lung disease, Candida pneumonia, Disseminated aspergillosis
Neurotoxicity, Paralysis, Sensory disturbance
Ventricular arrhythmia, Syncope, Ventricular tachyarrhythmia, Bradyarrhythmia, Arrhythmia, Electrocardiogram QT interval abnormal, Sinus bradycardia, Ventricular tachycardia, Electrocardiogram QT interval, Bradycardia, Long QT syndrome, Electrocardiogram QT prolonged, Paroxysmal arrhythmia, Electrocardiogram RR interval prolonged, Withdrawal arrhythmia, Electrocardiogram ST segment abnormal, Electrocardiogram T wave abnormal, Electrocardiogram U wave abnormal, Electrocardiogram right bundle branch block, Electrocardiogram ST elevation, Electrocardiogram QT shortening, Electrocardiogram QTc interval abnormal, Electrocardiogram PR interval abnormal, Electrocardiogram atrial pacing, Electrocardiogram DDD pacing mode.
Dysarthria, Ischaemic stroke, Hemiparesis, Thrombotic stroke, Ischaemic cerebral infarction, Cerebral thrombosis, Hemiplegia, Cerebral artery thrombosis, Dysarthria, Hypokinetic dysarthria, Hemiataxia, Vertebrobasilar stroke, Precerebral artery thrombosis, Hemiparesis, Ischaemic stroke, Thrombotic stroke, Ischaemic cerebral infarction, Cerebral thrombosis, Hemiplegia, Cerebral artery thrombosis, Dysarthria, Hypokinetic dysarthria, Hemiataxia, Vertebrobasilar stroke, Precerebral artery thrombosis
Galactorrhoea, Amenorrhoea, Galactocele, Menstrual disorder, Female reproductive tract disorder, Amenorrhoea-galactorrhoea syndrome, Pituitary amenorrhoea, Hypomenorrhoea, Oligomenorrhoea, Blood gonadotrophin abnormal, Ovarian disorder, Galactostasis, Amniorrhoea, Blood gonadotrophin, Galactosaemia, Galactorrhoea syndrome, Reproductive system disorder, Breast disorder, Endocrine disorder, Hormone level abnormal, Lactation disorder, Breast symptom, Reproductive system symptom, Endocrine symptom, Hormone level increased, Lactation abnormal.
Pulmonary oedema, Dyspnoea, Respiratory tract oedema, Gastrointestinal oedema, Acute pulmonary oedema, Gastric reflux, Oesophageal oedema, Respiratory symptom, Pulmonary pain, Non-cardiogenic pulmonary oedema, Visceral oedema, Gastric pneumatosis, Laryngeal oedema, Allergic oedema, Oedema due to cardiac disease, Gastrooesophageal reflux disease, Oropharyngeal oedema, Pulmonary hypertension, Pulmonary congestion, Circumoral oedema, Tongue oedema, Generalised oedema, Abdominal wall oedema, Gastric ulcer haemorrhage, Respiratory failure
Suicidal behaviour, Suicidal ideation, Hallucination, Psychiatric symptom, Psychotic symptom, Neuropsychiatric symptoms, Depression suicidal, Hallucination, visual, Hallucination, auditory, Hallucinations, mixed, Psychotic disorder, Hallucination, tactile, Hallucination, olfactory, Hallucination, gustatory, Schizophrenia, Depressive symptom, Acute psychosis, Psychotic behaviour, Hypnagogic hallucination, Depersonalisation/derealisation disorder, Hysterical psychosis, Schizoaffective disorder, Bipolar disorder
Lymphopenia, Leukopenia, Anemia, Neutropenia, Granulocytopenia, Cytopenia, Blood disorder, Haematotoxicity, Immunodeficiency, Pancytopenia, Bicytopenia, Bone marrow disorder, Anaemia, Leukocytopenia, Leukocytosis, White blood cell disorder, Leukoerythroblastosis, Microcytic anaemia, Anaemia macrocytic, Blood loss anaemia, Deficiency anaemia, Anaemia of malignant disease, Red blood cell abnormality, Immune-mediated cytopenia, Anaemia splenic
Neutropenia, Thrombocytopenia, Febrile neutropenia, Pseudomonal bacteraemia, Granulocytopenia, Pancytopenia, Neutropenic infection, Pseudomonal sepsis, Transfusion-related alloimmune neutropenia, Anemia, Infection, Hematological adverse events, Infusion-related reactions, Late-onset infections, Drug-induced liver injury, Tumor lysis syndrome, Hematologic adverse events, Alanine aminotransferase elevation, Aspartate aminotransferase elevation, Bilirubin elevation, Autoimmune cytopenia, Graft-versus-host disease, Non-hematological adverse events, Adverse events of special interest, Dose-limiting toxicities.
Neutropenia, Thrombocytopenia, Infusion related reaction, Anemia, Infusion related hypersensitivity reaction, Transfusion reaction, Allergic transfusion reaction, Anaphylactic transfusion reaction, Hypotensive transfusion reaction, Haemolytic transfusion reaction, Transfusion-related circulatory overload, Transfusion-associated dyspnoea, Acute haemolytic transfusion reaction, Immune thrombocytopenia, Pancytopenia, Granulocytopenia, Thrombocytopenic purpura, Immune-mediated pancytopenia, Neutropenic infection, Immune-mediated cytopenia, Cytopenia, Haematotoxicity, Anaemia, Injection related reaction, Blood product transfusion dependent
Thrombotic microangiopathy, Microangiopathic haemolytic anaemia, Haemolytic uraemic syndrome, Microangiopathy, Renal-limited thrombotic microangiopathy
Ruptured ectopic pregnancy, Ectopic pregnancy with contraceptive device, Ectopic pregnancy, Reproductive complication associated with device, Pregnancy with contraceptive device, Device failure, Fallopian tube perforation, Ectopic pregnancy under hormonal contraception, Intra-uterine contraceptive device removal, Abortion of ectopic pregnancy, Tubal rupture, Uterine rupture, Ovarian rupture, Cyst rupture, Implantation complication, Foreign body in reproductive tract, Fallopian tube obstruction, Peripartum haemorrhage, Ectopic pregnancy termination, Intra-uterine contraceptive device insertion, IUD migration, IUD expulsion, IUD displacement, IUD embedment, IUD perforation.
Haemolytic anaemia, Schistocytosis, Anisocytosis, Red blood cell schistocytes, Spherocytic anaemia, Platelet anisocytosis, Red blood cell anisocytes, Hyperthrombinaemia
Radiation enteritis, Ileal perforation, Intestinal perforation, Gastrointestinal perforation, Enteritis, Peritonitis, Radiation inflammation, Small intestinal perforation, Radiation mucositis, Radiation proctitis, Gastroenteritis radiation, Ileal ulcer perforation, Intestinal ulcer perforation, Small intestinal ulcer perforation, Radiotherapy to gastrointestinal tract, Radiotherapy to abdomen, Radiation associated pain, Radiation vasculitis, Appendicitis perforated, Radiation-induced bowel perforation, Acute radiation enteritis, Radiation-induced enteritis, Radiation-induced ileal perforation, Radiation-induced intestinal perforation, Radiation-induced gastrointestinal perforation.
Thrombocytopenia, Haemoptysis, Pulmonary alveolar haemorrhage, Diffuse alveolar damage, Pulmonary haemorrhage, Bronchial haemorrhage, Respiratory tract haemorrhage, Alveolar lung disease, Haemorrhagic pneumonia, Alveolitis, Acute lung injury, Pulmonary vascular disorder, Pulmonary congestion, Haemorrhagic disorder, Lung disorder, Respiratory failure, Acute respiratory failure, Coagulopathy, Thrombocytopenic purpura, Immune thrombocytopenia, Pharyngeal haemorrhage, Thoracic haemorrhage, Tracheal haemorrhage, Mouth haemorrhage, Pulmonary vasculitis
Tubulointerstitial nephritis, Nephritis, Acute cutaneous lupus erythematosus, Nephritis allergic, Lupus nephritis, Autoimmune nephritis, Immune-mediated nephritis, Immune-mediated renal disorder, Glomerulonephritis, Glomerulonephritis acute, Pemphigoid, Nephritic syndrome, Pyelonephritis acute, Autoimmune blistering disease, Bullous haemorrhagic dermatosis, Neutrophilic dermatosis, Dermatitis bullous, Pemphigus, Oedema due to renal disease, Oedematous kidney, Kidney infection, Perinephritis, Nephrectasia, Tubulointerstitial nephritis and uveitis syndrome, Nephritis haemorrhagic.
Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Angle closure glaucoma, Open angle glaucoma, Glaucoma traumatic
Acute generalised exanthematous pustulosis, Puerperal pyrexia, Tachycardia, Tachycardia paroxysmal
Femoral neck fracture, Osteonecrosis, Osteonecrosis of jaw, Femoral facial syndrome, Osteosclerosis, Osteoradionecrosis, Chondronecrosis, Osteosis
Subcutaneous edema, Generalized sensory neuropathy, Erythematous-desquamative lesions, Peripheral sensory neuropathy, Skin oedema, Rash erythematous, Cutaneous symptom, Sensory neuropathy, Polyneuropathy, Localised oedema, Peripheral nerve lesion, Neuropathy peripheral, Toxic neuropathy, Acute polyneuropathy, Autoimmune neuropathy, Erythema, Generalised oedema, Demyelinating polyneuropathy, Axonal neuropathy, Subacute inflammatory demyelinating polyneuropathy, Acute motor-sensory axonal neuropathy, Plantar erythema, Erythema multiforme, Dermatitis bullous, Allergic oedema
Gastrointestinal discomfort, Gastrointestinal tract irritation, Gastrointestinal pain, Abdominal discomfort, Gastrointestinal disorder, Gastrointestinal mucosal disorder, Oesophageal discomfort, Oesophageal irritation, Anorectal discomfort, Essential tremor, Dystonic tremor, Tremor, Postural tremor, Resting tremor, Psychogenic tremor, Gastrointestinal oedema, Gastrointestinal motility disorder, Hand tremor, Intense gastro-intestinal discomfort, Severe hand tremor, Unbearable adverse effects, Edema, Intermittent edema, Unbearable adverse effects due to immunosuppressants.
Hypokalaemia, Hypomagnesaemia, Hypocalcaemia
Hypotension, Respiratory depression, Hypoventilation, Bradycardia, Hypoxia, Dyspnoea, Nocturnal dyspnoea, Orthostatic hypotension, Hyporeflexia, Muscle hypoxia, Sinus bradycardia, Diastolic hypotension, Central bradycardia, Respiratory failure, Sleep apnoea syndrome, Vasoconstriction, Hypocapnia, Cardio-respiratory distress, Paroxysmal nocturnal dyspnoea, Hypotension, Respiratory distress, Apnea, Tachypnea, Stridor, Strenal retractions.
Hyperkalaemia, Anaemia, Hypoproteinaemia, Hyperuricaemia, Hyponatraemia, Hypervolaemia, Hyperphosphataemia, Alkalosis hypokalaemic, Hydraemia, Urinary ascites, Blood osmolarity, Hyperaemia
Haemorrhage, Haematuria, Deep vein thrombosis, Thrombosis, Vena cava thrombosis, Gastrointestinal haemorrhage, Intestinal haemorrhage, Blood urine, Albuminuria, Proteinuria, Haematinuria, Coagulopathy, Thrombophlebitis, Pulmonary thrombosis, Embolism venous, Mesenteric haemorrhage, Venous thrombosis, Visceral venous thrombosis, Pelvic venous thrombosis, Catheter site thrombosis, Shunt thrombosis, Blood thrombin, Blood thromboplastin, Thrombin time, Lower gastrointestinal haemorrhage, Haemorrhagic vasculitis
Epistaxis, Melanaemia, Anaemia, Haematinuria, Blood loss anaemia
Thrombocytopenia, Neutropenia, Pancytopenia, Liver disorder, Granulocytopenia, Autoimmune pancytopenia, Monocytopenia, Immune-mediated pancytopenia, Cytopenia, Liver injury, Haematochezia, Hepatic function abnormal, Haematotoxicity, Platelet disorder, Blood disorder, Red blood cell abnormality, Immune thrombocytopenia, Autoimmune neutropenia, Thrombocytopenic purpura, Neutrophil function disorder, Reticuloendothelial dysfunction, Neutropenic infection, Liver function test abnormal, Immune-mediated cytopenia, Amegakaryocytic thrombocytopenia, Hepatotoxicity
Long QT syndrome, Ventricular tachyarrhythmia, Electrocardiogram QT prolonged, Ventricular tachycardia, Torsade de pointes, Electrocardiogram QT interval abnormal, Ventricular arrhythmia, Paroxysmal arrhythmia, Electrocardiogram QRS complex prolonged, Arrhythmia, Tachyarrhythmia, Ventricular dyskinesia.
Meningitis aseptic, Meningitis, Meningitis-retention syndrome, Urinary retention, Pyramidal tract syndrome, Meningeal disorder, Meningitis eosinophilic, Meningoradiculitis, Cerebrospinal fluid retention, Meningitis aspergillus, Meningitis mumps, Meningitis exserohilum, Meningitis, Meningitis aseptic, Meningitis, Meningitis-retention syndrome, Urinary retention, Pyramidal tract syndrome, Meningeal disorder, Meningitis eosinophilic, Meningoradiculitis, Cerebrospinal fluid retention, Meningitis aspergillus, Meningitis mumps, Meningitis exserohilum
Pancreatitis, Pancreatitis acute, Pancreatitis haemorrhagic, Pancreatitis chronic, Pancreatic disorder, Pancreatitis bacterial, Pancreatic infarction, Pancreatitis viral, Pancreatitis mumps, Hypertriglyceridaemia, Blood triglycerides abnormal, Pancreatic enzymes abnormal, Pancreatic enzyme abnormality, Autoimmune pancreatitis, Obstructive pancreatitis, Oedematous pancreatitis, Lupus pancreatitis, Ischaemic pancreatitis, Pancreas infection, Ultrasound pancreas abnormal, Biopsy pancreas abnormal, Computerised tomogram pancreas abnormal, Pancreatitis, Pancreatic enzymes increased, Pancreatic function abnormal
Osteoporotic fracture, Renal failure, Fracture infection, Osteomyelitis, Kidney infection, Multiple fractures.
Mucocutaneous haemorrhage, Skin haemorrhage, Haemorrhagic disorder, Rectal haemorrhage, Mouth haemorrhage, Eyelid bleeding, Periorbital haematoma, Skin ulcer haemorrhage, Shock haemorrhagic, Eye haemorrhage, Vitreous haemorrhage, Retinopathy haemorrhagic, Retinal haemorrhage, Periorbital haemorrhage, Haemorrhage, Bleeding, Petechiae, Bruising, Mucosal hemorrhages, Cutaneous bleeding, Internal hemorrhages, Intracranial hemorrhage, Life-threatening bleeding, Severe bleeding symptoms, Hemorrhagic shock
Atrial fibrillation, Atrial flutter, Ventricular pre-excitation, Ventricular tachyarrhythmia, Palpitations, Arrhythmia, Tachycardia, Cardiac discomfort, Ventricular arrhythmia, Paroxysmal arrhythmia, Cardiac flutter, Bradyarrhythmia, Bradycardia foetal, Neonatal bradyarrhythmia, Bradycardia neonatal.
Neutropenia.
Toxicity to various agents, Toxicity
Serotonin syndrome, Hyponatraemic encephalopathy, Hyponatraemia, Hypoxic-ischaemic encephalopathy, Hyponatraemic coma, Hyponatraemic seizure, Encephalitis lethargica, Hyponatraemic syndrome, Hyposmia, Lethargy, Confusion, Insomnia, Tachycardia, Restlessness, Psychomotor slowing, Myoclonic jerks, Hyperreflexia, Seizure, Coma, Encephalitis, Meningitis, Empyema, Neurologic complications, Devastating neurologic complications, Neuroendocrine tumor, Autoimmune meningoencephalomyelitis
Hand-foot-genital syndrome, diarrhea, nausea, vomiting, fatigue, anemia, neutropenia, thrombocytopenia, hypertension, proteinuria, bleeding, wound healing complications, gastrointestinal perforation, fistula, arterial thromboembolic events, venous thromboembolic events, congestive heart failure, posterior reversible encephalopathy syndrome, osteonecrosis of the jaw, infusion reactions, hypersensitivity reactions, skin reactions, mucosal inflammation, stomatitis, palmar-plantar erythrodysesthesia.
Photophobia, Eye pain, Ocular hypertension, Eye inflammation, Keratitis, Corneal irritation, Eye swelling, Conjunctival irritation, Corneal epithelium defect, Eye symptom, Ocular discomfort, Abnormal sensation in eye, Eye oedema, Periorbital oedema, Conjunctival oedema, Keratopathy, Corneal disorder, Ocular toxicity, Scleral hyperaemia, Foreign body sensation in eyes, Eyelid oedema, Photokeratitis, Corneal defect, Corneal thinning, Borderline glaucoma, Ocular hyperaemia
Anxiety, Depression, Anxiety disorder, Depressed mood, Panic attack, Depressive symptom, Social anxiety disorder, Illness anxiety disorder, Major depression, Agitated depression, Emotional distress, Affective disorder, Anticipatory anxiety, Adjustment disorder with mixed anxiety and depressed mood, Feeling of despair, Negative thoughts, Generalised anxiety disorder, Postpartum anxiety, Persistent depressive disorder, Adjustment disorder with anxiety, Psychiatric symptom, Mental disorder, Dysphoria, Nervousness, Obsessive thoughts
Somnolence, Hypotension, Orthostatic hypotension, Hypotensive crisis, Procedural hypotension, Blood pressure immeasurable, Hypoventilation, Hypoxia intolerance, Post procedural hypotension, Hyporesponsive to stimuli, Somnolence neonatal, Hyposomnia, Hypotension, Orthostatic hypotension, Hypotension, Somnolence, Hypotension, Hypotensive crisis, Procedural hypotension, Hypoventilation, Hypoxia intolerance, Post procedural hypotension, Hyporesponsive to stimuli, Somnolence, Hypotension
Conjunctivitis allergic, Conjunctivitis, Conjunctival irritation, Conjunctival follicles, Allergic keratitis, Foreign body sensation in eyes, Blepharitis allergic, Conjunctival oedema, Conjunctival hyperemia, Itching, Tearing, Dry mouth, Headache, Sedation, Drowsiness, Hypotension, Blurred vision, Ocular allergy, Follicular reaction, Bulbar conjunctival follicular reactions, Tarsal conjunctival follicular reactions, Discomfort, IOP elevation, IOP increase, Loss of IOP control.
Cardiac tamponade, Pericarditis lupus, Lupus myocarditis, Pericarditis, Cardiovascular function test abnormal, Cardiac function test abnormal, Liver function test abnormal, Pericarditis rheumatic, Pericardial drainage test abnormal, Pericarditis, Pericarditis infective, Neutrophil function test abnormal, Pericarditis syphilitic, Viral pericarditis, Cardiac tamponade, Pericarditis lupus, Lupus myocarditis, Pericarditis, Cardiovascular function test abnormal, Cardiac function test abnormal, Liver function test abnormal, Pericarditis rheumatic, Pericarditis infective, Neutrophil function test abnormal, Pericarditis syphilitic, Viral pericarditis
Cardiac arrest, Myocardial infarction, Hypotension, Bradycardia, Cardiac death, Cardio-respiratory arrest, Arrhythmia, Ventricular arrhythmia, Cardiogenic shock, Anaesthetic complication cardiac, Cardio-respiratory distress, Acute myocardial infarction, Myocardial ischaemia, Myocardial injury, Myocardial hypoxia, Hypotensive crisis, ECG signs of myocardial infarction, Cardiac failure, Resuscitation, Post cardiac arrest syndrome, Sinus bradycardia, Central bradycardia, Bradyarrhythmia, Diastolic hypotension, Ventricular tachyarrhythmia

In [86]:
top_answer_df.rename(columns={"pred_reaction": "pred_reaction_norank"}, inplace=True)
top_answer_df["pred_reaction"] = top_answer_df["_map"].apply(
    lambda x: [reaction.strip() for reaction in x.split(",") if reaction.strip()]
)
# top_answer_df["pred_reaction"] = top_answer_df["pred_reaction"].apply(
#     lambda reactions: [f"'{r}'" for r in reactions]
# )

In [87]:
top_answer_df['pred_reaction'].iloc[0]

['Cyanosis',
 'Methaemoglobinaemia',
 'Hypoxia',
 'Cyanosis central',
 'Cyanopsia',
 'Dysglobulinaemia',
 'Congenital methaemoglobinaemia',
 'Hypochromasia']

In [88]:
from biodex.metrics import compute_precision, compute_rank_precision, compute_recall

def compute_metrics(res_df, gt_col_name="reactions_list", pred_col_name="pred_reaction") -> pd.DataFrame:
    res_df["rank_precision@5"] = res_df.apply(
        lambda x: compute_rank_precision(x[gt_col_name], x[pred_col_name], cutoff=5),
        axis=1,
    )
    res_df["rank-precision@10"] = res_df.apply(
        lambda x: compute_rank_precision(x[gt_col_name], x[pred_col_name], cutoff=10),
        axis=1,
    )
    res_df["rank-precision@25"] = res_df.apply(
        lambda x: compute_rank_precision(x[gt_col_name], x[pred_col_name], cutoff=25),
        axis=1,
    )


    for k in [5, 10, 20, 50, 100, 200, 300, 400, 500]:
        res_df[f"recall@{k}"] = res_df.apply(lambda x: compute_recall(x[gt_col_name], x[pred_col_name], k), axis=1)

    res_df["precision@5"] = res_df.apply(lambda x: compute_precision(x[gt_col_name], x[pred_col_name], 5), axis=1)
    res_df["precision@10"] = res_df.apply(lambda x: compute_precision(x[gt_col_name], x[pred_col_name], 10), axis=1)

    res_df["num_ids"] = res_df.apply(lambda x: len(x[pred_col_name]), axis=1)

    # take subset of df with metrics
    df = res_df[[col for col in res_df.columns if "@" in col or "latency" in col or "num_ids" in col]]

    return df

In [89]:

metrics_df = compute_metrics(top_answer_df, gt_col_name="reactions_list", pred_col_name="pred_reaction")

gt_ids: ['Facial paralysis', 'Methaemoglobinaemia'], type: <class 'list'>
ids: ['Cyanosis', 'Methaemoglobinaemia', 'Hypoxia', 'Cyanosis central', 'Cyanopsia', 'Dysglobulinaemia', 'Congenital methaemoglobinaemia', 'Hypochromasia'], type: <class 'list'>
gt_ids: ['Haemoglobin decreased', 'Off label use', 'Retroperitoneal haemorrhage'], type: <class 'list'>
ids: ['Thrombocytopenia', 'Haemolytic anaemia', 'Autoimmune haemolytic anaemia', 'Autoimmune anaemia', 'Thrombocytopenia', 'Platelet dysfunction', 'Renal impairment', 'Renal failure', 'Autoimmune pancytopenia', 'Renal haemorrhage', 'Thrombocytopenia', 'Haemolytic anaemia', 'Autoimmune haemolytic anaemia', 'Autoimmune anaemia', 'Platelet dysfunction', 'Renal impairment', 'Renal failure', 'Autoimmune pancytopenia', 'Renal haemorrhage', 'Thrombocytopenia', 'Haemolytic anaemia', 'Autoimmune haemolytic anaemia', 'Autoimmune anaemia', 'Platelet dysfunction', 'Renal impairment.'], type: <class 'list'>
gt_ids: ['Cholecystitis acute', 'Haemobilia', 'Haemorrhagic ascites', 'Haemorrhagic cholecystitis'], type: <class 'list'>
ids: ['Haemorrhagic cholecystitis', 'Haemobilia', 'Haemorrhage', 'Gastrointestinal haemorrhage', 'Upper gastrointestinal haemorrhage', 'Gastric haemorrhage', 'Gastric ulcer haemorrhage', 'Haemorrhagic gastritis', 'Haemorrhagic cyst', 'Cholecystitis', 'Enterocolitis haemorrhagic', 'Rectal haemorrhage', 'Diarrhoea haemorrhagic', 'Haemorrhagic erosive gastritis', 'Gastrointestinal vascular malformation haemorrhagic', 'Oesophageal ulcer haemorrhage', 'Oesophageal haemorrhage', 'Duodenal ulcer haemorrhage', 'Haematochezia', 'Haemorrhagic ascites', 'Abdominal wall haemorrhage', 'Intra-abdominal haemorrhage', 'Cholecystocholangitis', 'Cholelithiasis', 'Haemorrhage prophylaxis'], type: <class 'list'>
gt_ids: ['Decreased appetite', 'Disease progression', 'Dyspnoea', 'Fatigue'], type: <class 'list'>
ids: ['Transaminases abnormal', 'Hypertransaminasaemia', 'Gastrointestinal mucosa hyperaemia'], type: <class 'list'>
gt_ids: ['Bronchopulmonary aspergillosis', 'Obliterative bronchiolitis', 'Off label use', 'Respiratory failure'], type: <class 'list'>
ids: ['Bronchiolitis obliterans', 'Pulmonary aspergillosis', 'Bronchitis fungal', 'Respiratory tract infection fungal', 'Pneumonia fungal', 'Aspergilloma', 'Bronchitis mycoplasmal', 'Pulmonary mucormycosis', 'Bronchitis pneumococcal', 'Pneumonia toxoplasmal', 'Sinusitis aspergillus', 'Acute pulmonary histoplasmosis', 'Meningitis aspergillus', 'Upper respiratory fungal infection', 'Oro-pharyngeal aspergillosis', 'Pulmonary granuloma', 'Alveolitis', 'Pneumonitis', 'Cerebral aspergillosis', 'Bronchial ulceration', 'Eosinophilic bronchitis', 'Pulmonary lymphangiectasia', 'Bronchostenosis', 'Alveolar lung disease', 'Candida pneumonia', 'Disseminated aspergillosis'], type: <class 'list'>
gt_ids: ['Neurotoxicity', 'Overdose', 'Paralysis'], type: <class 'list'>
ids: ['Neurotoxicity', 'Paralysis', 'Sensory disturbance'], type: <class 'list'>
gt_ids: ['Bradycardia', 'Brugada syndrome', 'Drug ineffective', 'Electrocardiogram abnormal', 'Unmasking of previously unidentified disease'], type: <class 'list'>
ids: ['Ventricular arrhythmia', 'Syncope', 'Ventricular tachyarrhythmia', 'Bradyarrhythmia', 'Arrhythmia', 'Electrocardiogram QT interval abnormal', 'Sinus bradycardia', 'Ventricular tachycardia', 'Electrocardiogram QT interval', 'Bradycardia', 'Long QT syndrome', 'Electrocardiogram QT prolonged', 'Paroxysmal arrhythmia', 'Electrocardiogram RR interval prolonged', 'Withdrawal arrhythmia', 'Electrocardiogram ST segment abnormal', 'Electrocardiogram T wave abnormal', 'Electrocardiogram U wave abnormal', 'Electrocardiogram right bundle branch block', 'Electrocardiogram ST elevation', 'Electrocardiogram QT shortening', 'Electrocardiogram QTc interval abnormal', 'Electrocardiogram PR interval abnormal', 'Electrocardiogram atrial pacing', 'Electrocardiogram DDD pacing mode.'], type: <class 'list'>
gt_ids: ['Dysarthria', 'Hemiparesis'], type: <class 'list'>
ids: ['Dysarthria', 'Ischaemic stroke', 'Hemiparesis', 'Thrombotic stroke', 'Ischaemic cerebral infarction', 'Cerebral thrombosis', 'Hemiplegia', 'Cerebral artery thrombosis', 'Dysarthria', 'Hypokinetic dysarthria', 'Hemiataxia', 'Vertebrobasilar stroke', 'Precerebral artery thrombosis', 'Hemiparesis', 'Ischaemic stroke', 'Thrombotic stroke', 'Ischaemic cerebral infarction', 'Cerebral thrombosis', 'Hemiplegia', 'Cerebral artery thrombosis', 'Dysarthria', 'Hypokinetic dysarthria', 'Hemiataxia', 'Vertebrobasilar stroke', 'Precerebral artery thrombosis'], type: <class 'list'>
gt_ids: ['Condition aggravated'], type: <class 'list'>
ids: ['Galactorrhoea', 'Amenorrhoea', 'Galactocele', 'Menstrual disorder', 'Female reproductive tract disorder', 'Amenorrhoea-galactorrhoea syndrome', 'Pituitary amenorrhoea', 'Hypomenorrhoea', 'Oligomenorrhoea', 'Blood gonadotrophin abnormal', 'Ovarian disorder', 'Galactostasis', 'Amniorrhoea', 'Blood gonadotrophin', 'Galactosaemia', 'Galactorrhoea syndrome', 'Reproductive system disorder', 'Breast disorder', 'Endocrine disorder', 'Hormone level abnormal', 'Lactation disorder', 'Breast symptom', 'Reproductive system symptom', 'Endocrine symptom', 'Hormone level increased', 'Lactation abnormal.'], type: <class 'list'>
gt_ids: ['Condition aggravated', 'Dyspnoea', 'Gastrooesophageal reflux disease', 'Product use in unapproved indication', 'Pulmonary oedema'], type: <class 'list'>
ids: ['Pulmonary oedema', 'Dyspnoea', 'Respiratory tract oedema', 'Gastrointestinal oedema', 'Acute pulmonary oedema', 'Gastric reflux', 'Oesophageal oedema', 'Respiratory symptom', 'Pulmonary pain', 'Non-cardiogenic pulmonary oedema', 'Visceral oedema', 'Gastric pneumatosis', 'Laryngeal oedema', 'Allergic oedema', 'Oedema due to cardiac disease', 'Gastrooesophageal reflux disease', 'Oropharyngeal oedema', 'Pulmonary hypertension', 'Pulmonary congestion', 'Circumoral oedema', 'Tongue oedema', 'Generalised oedema', 'Abdominal wall oedema', 'Gastric ulcer haemorrhage', 'Respiratory failure'], type: <class 'list'>
gt_ids: ['Drug ineffective', 'Off label use'], type: <class 'list'>
ids: ['Suicidal behaviour', 'Suicidal ideation', 'Hallucination', 'Psychiatric symptom', 'Psychotic symptom', 'Neuropsychiatric symptoms', 'Depression suicidal', 'Hallucination', 'visual', 'Hallucination', 'auditory', 'Hallucinations', 'mixed', 'Psychotic disorder', 'Hallucination', 'tactile', 'Hallucination', 'olfactory', 'Hallucination', 'gustatory', 'Schizophrenia', 'Depressive symptom', 'Acute psychosis', 'Psychotic behaviour', 'Hypnagogic hallucination', 'Depersonalisation/derealisation disorder', 'Hysterical psychosis', 'Schizoaffective disorder', 'Bipolar disorder'], type: <class 'list'>
gt_ids: ['Abdominal pain', 'Alopecia', 'Anaemia', 'Blood albumin decreased', 'Colorectal adenocarcinoma', 'Death', 'Deep vein thrombosis', 'Drug ineffective', 'Leukopenia', 'Lymphopenia', 'Neuropathy peripheral', 'Neutropenia', 'Sepsis'], type: <class 'list'>
ids: ['Lymphopenia', 'Leukopenia', 'Anemia', 'Neutropenia', 'Granulocytopenia', 'Cytopenia', 'Blood disorder', 'Haematotoxicity', 'Immunodeficiency', 'Pancytopenia', 'Bicytopenia', 'Bone marrow disorder', 'Anaemia', 'Leukocytopenia', 'Leukocytosis', 'White blood cell disorder', 'Leukoerythroblastosis', 'Microcytic anaemia', 'Anaemia macrocytic', 'Blood loss anaemia', 'Deficiency anaemia', 'Anaemia of malignant disease', 'Red blood cell abnormality', 'Immune-mediated cytopenia', 'Anaemia splenic'], type: <class 'list'>
gt_ids: ['Basal cell carcinoma', 'CD4 lymphocytes decreased', 'Neutropenia', 'Thrombocytopenia', 'Toxicity to various agents'], type: <class 'list'>
ids: ['Neutropenia', 'Thrombocytopenia', 'Febrile neutropenia', 'Pseudomonal bacteraemia', 'Granulocytopenia', 'Pancytopenia', 'Neutropenic infection', 'Pseudomonal sepsis', 'Transfusion-related alloimmune neutropenia', 'Anemia', 'Infection', 'Hematological adverse events', 'Infusion-related reactions', 'Late-onset infections', 'Drug-induced liver injury', 'Tumor lysis syndrome', 'Hematologic adverse events', 'Alanine aminotransferase elevation', 'Aspartate aminotransferase elevation', 'Bilirubin elevation', 'Autoimmune cytopenia', 'Graft-versus-host disease', 'Non-hematological adverse events', 'Adverse events of special interest', 'Dose-limiting toxicities.'], type: <class 'list'>
gt_ids: ['Tumour lysis syndrome'], type: <class 'list'>
ids: ['Neutropenia', 'Thrombocytopenia', 'Infusion related reaction', 'Anemia', 'Infusion related hypersensitivity reaction', 'Transfusion reaction', 'Allergic transfusion reaction', 'Anaphylactic transfusion reaction', 'Hypotensive transfusion reaction', 'Haemolytic transfusion reaction', 'Transfusion-related circulatory overload', 'Transfusion-associated dyspnoea', 'Acute haemolytic transfusion reaction', 'Immune thrombocytopenia', 'Pancytopenia', 'Granulocytopenia', 'Thrombocytopenic purpura', 'Immune-mediated pancytopenia', 'Neutropenic infection', 'Immune-mediated cytopenia', 'Cytopenia', 'Haematotoxicity', 'Anaemia', 'Injection related reaction', 'Blood product transfusion dependent'], type: <class 'list'>
gt_ids: ['Acute kidney injury', 'Anaemia', 'Disease progression', 'Haematotoxicity', 'Microangiopathic haemolytic anaemia', 'Mucosal inflammation', 'Neoplasm progression', 'Neutropenia', 'Renal failure', 'Thrombocytopenia', 'Thrombotic microangiopathy'], type: <class 'list'>
ids: ['Thrombotic microangiopathy', 'Microangiopathic haemolytic anaemia', 'Haemolytic uraemic syndrome', 'Microangiopathy', 'Renal-limited thrombotic microangiopathy'], type: <class 'list'>
gt_ids: ['Amenorrhoea', 'Device issue', 'Drug ineffective', 'Ectopic pregnancy with contraceptive device', 'Exposure during pregnancy', 'Haemoperitoneum', 'Ruptured ectopic pregnancy'], type: <class 'list'>
ids: ['Ruptured ectopic pregnancy', 'Ectopic pregnancy with contraceptive device', 'Ectopic pregnancy', 'Reproductive complication associated with device', 'Pregnancy with contraceptive device', 'Device failure', 'Fallopian tube perforation', 'Ectopic pregnancy under hormonal contraception', 'Intra-uterine contraceptive device removal', 'Abortion of ectopic pregnancy', 'Tubal rupture', 'Uterine rupture', 'Ovarian rupture', 'Cyst rupture', 'Implantation complication', 'Foreign body in reproductive tract', 'Fallopian tube obstruction', 'Peripartum haemorrhage', 'Ectopic pregnancy termination', 'Intra-uterine contraceptive device insertion', 'IUD migration', 'IUD expulsion', 'IUD displacement', 'IUD embedment', 'IUD perforation.'], type: <class 'list'>
gt_ids: ['Atypical haemolytic uraemic syndrome', 'Hepatic haematoma', 'Off label use'], type: <class 'list'>
ids: ['Haemolytic anaemia', 'Schistocytosis', 'Anisocytosis', 'Red blood cell schistocytes', 'Spherocytic anaemia', 'Platelet anisocytosis', 'Red blood cell anisocytes', 'Hyperthrombinaemia'], type: <class 'list'>
gt_ids: ['Gastroenteritis radiation', 'Ileal perforation'], type: <class 'list'>
ids: ['Radiation enteritis', 'Ileal perforation', 'Intestinal perforation', 'Gastrointestinal perforation', 'Enteritis', 'Peritonitis', 'Radiation inflammation', 'Small intestinal perforation', 'Radiation mucositis', 'Radiation proctitis', 'Gastroenteritis radiation', 'Ileal ulcer perforation', 'Intestinal ulcer perforation', 'Small intestinal ulcer perforation', 'Radiotherapy to gastrointestinal tract', 'Radiotherapy to abdomen', 'Radiation associated pain', 'Radiation vasculitis', 'Appendicitis perforated', 'Radiation-induced bowel perforation', 'Acute radiation enteritis', 'Radiation-induced enteritis', 'Radiation-induced ileal perforation', 'Radiation-induced intestinal perforation', 'Radiation-induced gastrointestinal perforation.'], type: <class 'list'>
gt_ids: ['Labelled drug-drug interaction issue', 'Pulmonary alveolar haemorrhage', 'Pulmonary haemorrhage', 'Thrombocytopenia'], type: <class 'list'>
ids: ['Thrombocytopenia', 'Haemoptysis', 'Pulmonary alveolar haemorrhage', 'Diffuse alveolar damage', 'Pulmonary haemorrhage', 'Bronchial haemorrhage', 'Respiratory tract haemorrhage', 'Alveolar lung disease', 'Haemorrhagic pneumonia', 'Alveolitis', 'Acute lung injury', 'Pulmonary vascular disorder', 'Pulmonary congestion', 'Haemorrhagic disorder', 'Lung disorder', 'Respiratory failure', 'Acute respiratory failure', 'Coagulopathy', 'Thrombocytopenic purpura', 'Immune thrombocytopenia', 'Pharyngeal haemorrhage', 'Thoracic haemorrhage', 'Tracheal haemorrhage', 'Mouth haemorrhage', 'Pulmonary vasculitis'], type: <class 'list'>
gt_ids: ['Lichenoid keratosis', 'Pemphigoid', 'Skin toxicity', 'Tubulointerstitial nephritis'], type: <class 'list'>
ids: ['Tubulointerstitial nephritis', 'Nephritis', 'Acute cutaneous lupus erythematosus', 'Nephritis allergic', 'Lupus nephritis', 'Autoimmune nephritis', 'Immune-mediated nephritis', 'Immune-mediated renal disorder', 'Glomerulonephritis', 'Glomerulonephritis acute', 'Pemphigoid', 'Nephritic syndrome', 'Pyelonephritis acute', 'Autoimmune blistering disease', 'Bullous haemorrhagic dermatosis', 'Neutrophilic dermatosis', 'Dermatitis bullous', 'Pemphigus', 'Oedema due to renal disease', 'Oedematous kidney', 'Kidney infection', 'Perinephritis', 'Nephrectasia', 'Tubulointerstitial nephritis and uveitis syndrome', 'Nephritis haemorrhagic.'], type: <class 'list'>
gt_ids: ['Angle closure glaucoma', 'Choroidal effusion'], type: <class 'list'>
ids: ['Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Angle closure glaucoma', 'Open angle glaucoma', 'Glaucoma traumatic'], type: <class 'list'>
gt_ids: ['Acute generalised exanthematous pustulosis', 'Drug ineffective', 'Hypotension', 'Tachycardia', 'Tachypnoea'], type: <class 'list'>
ids: ['Acute generalised exanthematous pustulosis', 'Puerperal pyrexia', 'Tachycardia', 'Tachycardia paroxysmal'], type: <class 'list'>
gt_ids: ['Acute hepatic failure', 'Acute respiratory failure', 'Anaemia', 'Cardiac arrest', 'Cardiac failure acute', 'Decreased appetite', 'Dehydration', 'Diarrhoea', 'Disseminated intravascular coagulation', 'Dyspnoea', 'Electrolyte imbalance', 'Enterobacter infection', 'Haemophagocytic lymphohistiocytosis', 'Hypoproteinaemia', 'Multiple organ dysfunction syndrome', 'Nausea', 'Oliguria', 'Pyrexia', 'Shock', 'Splenomegaly', "Still's disease", 'Treatment noncompliance', 'Vomiting'], type: <class 'list'>
ids: ['Femoral neck fracture', 'Osteonecrosis', 'Osteonecrosis of jaw', 'Femoral facial syndrome', 'Osteosclerosis', 'Osteoradionecrosis', 'Chondronecrosis', 'Osteosis'], type: <class 'list'>
gt_ids: ['Erythema', 'Leiomyosarcoma', 'Leiomyosarcoma metastatic', 'Oedema peripheral', 'Off label use', 'Peripheral sensory neuropathy', 'Product use in unapproved indication', 'Skin exfoliation'], type: <class 'list'>
ids: ['Subcutaneous edema', 'Generalized sensory neuropathy', 'Erythematous-desquamative lesions', 'Peripheral sensory neuropathy', 'Skin oedema', 'Rash erythematous', 'Cutaneous symptom', 'Sensory neuropathy', 'Polyneuropathy', 'Localised oedema', 'Peripheral nerve lesion', 'Neuropathy peripheral', 'Toxic neuropathy', 'Acute polyneuropathy', 'Autoimmune neuropathy', 'Erythema', 'Generalised oedema', 'Demyelinating polyneuropathy', 'Axonal neuropathy', 'Subacute inflammatory demyelinating polyneuropathy', 'Acute motor-sensory axonal neuropathy', 'Plantar erythema', 'Erythema multiforme', 'Dermatitis bullous', 'Allergic oedema'], type: <class 'list'>
gt_ids: ['Abdominal discomfort', 'Drug intolerance', 'Tremor'], type: <class 'list'>
ids: ['Gastrointestinal discomfort', 'Gastrointestinal tract irritation', 'Gastrointestinal pain', 'Abdominal discomfort', 'Gastrointestinal disorder', 'Gastrointestinal mucosal disorder', 'Oesophageal discomfort', 'Oesophageal irritation', 'Anorectal discomfort', 'Essential tremor', 'Dystonic tremor', 'Tremor', 'Postural tremor', 'Resting tremor', 'Psychogenic tremor', 'Gastrointestinal oedema', 'Gastrointestinal motility disorder', 'Hand tremor', 'Intense gastro-intestinal discomfort', 'Severe hand tremor', 'Unbearable adverse effects', 'Edema', 'Intermittent edema', 'Unbearable adverse effects due to immunosuppressants.'], type: <class 'list'>
gt_ids: ['Diarrhoea', 'Electrocardiogram QT prolonged', 'Fatigue', 'Hypocalcaemia', 'Hypokalaemia', 'Hypomagnesaemia', 'Hypophosphataemia'], type: <class 'list'>
ids: ['Hypokalaemia', 'Hypomagnesaemia', 'Hypocalcaemia'], type: <class 'list'>
gt_ids: ['Procedural haemorrhage'], type: <class 'list'>
ids: ['Hypotension', 'Respiratory depression', 'Hypoventilation', 'Bradycardia', 'Hypoxia', 'Dyspnoea', 'Nocturnal dyspnoea', 'Orthostatic hypotension', 'Hyporeflexia', 'Muscle hypoxia', 'Sinus bradycardia', 'Diastolic hypotension', 'Central bradycardia', 'Respiratory failure', 'Sleep apnoea syndrome', 'Vasoconstriction', 'Hypocapnia', 'Cardio-respiratory distress', 'Paroxysmal nocturnal dyspnoea', 'Hypotension', 'Respiratory distress', 'Apnea', 'Tachypnea', 'Stridor', 'Strenal retractions.'], type: <class 'list'>
gt_ids: ['Abortion spontaneous', 'Maternal exposure during pregnancy'], type: <class 'list'>
ids: ['Hyperkalaemia', 'Anaemia', 'Hypoproteinaemia', 'Hyperuricaemia', 'Hyponatraemia', 'Hypervolaemia', 'Hyperphosphataemia', 'Alkalosis hypokalaemic', 'Hydraemia', 'Urinary ascites', 'Blood osmolarity', 'Hyperaemia'], type: <class 'list'>
gt_ids: ['Drug ineffective'], type: <class 'list'>
ids: ['Haemorrhage', 'Haematuria', 'Deep vein thrombosis', 'Thrombosis', 'Vena cava thrombosis', 'Gastrointestinal haemorrhage', 'Intestinal haemorrhage', 'Blood urine', 'Albuminuria', 'Proteinuria', 'Haematinuria', 'Coagulopathy', 'Thrombophlebitis', 'Pulmonary thrombosis', 'Embolism venous', 'Mesenteric haemorrhage', 'Venous thrombosis', 'Visceral venous thrombosis', 'Pelvic venous thrombosis', 'Catheter site thrombosis', 'Shunt thrombosis', 'Blood thrombin', 'Blood thromboplastin', 'Thrombin time', 'Lower gastrointestinal haemorrhage', 'Haemorrhagic vasculitis'], type: <class 'list'>
gt_ids: ['Anaemia', 'Basal cell carcinoma', 'Epistaxis', 'Haematuria', 'Haemorrhage', 'Hyperhomocysteinaemia', 'Hypertensive heart disease', 'Melaena', 'Myocardial ischaemia', 'Transitional cell carcinoma'], type: <class 'list'>
ids: ['Epistaxis', 'Melanaemia', 'Anaemia', 'Haematinuria', 'Blood loss anaemia'], type: <class 'list'>
gt_ids: ['Aplastic anaemia'], type: <class 'list'>
ids: ['Thrombocytopenia', 'Neutropenia', 'Pancytopenia', 'Liver disorder', 'Granulocytopenia', 'Autoimmune pancytopenia', 'Monocytopenia', 'Immune-mediated pancytopenia', 'Cytopenia', 'Liver injury', 'Haematochezia', 'Hepatic function abnormal', 'Haematotoxicity', 'Platelet disorder', 'Blood disorder', 'Red blood cell abnormality', 'Immune thrombocytopenia', 'Autoimmune neutropenia', 'Thrombocytopenic purpura', 'Neutrophil function disorder', 'Reticuloendothelial dysfunction', 'Neutropenic infection', 'Liver function test abnormal', 'Immune-mediated cytopenia', 'Amegakaryocytic thrombocytopenia', 'Hepatotoxicity'], type: <class 'list'>
gt_ids: ['Blood creatinine increased', 'Blood urea increased', 'Bradyarrhythmia', 'Bundle branch block left', 'Congestive cardiomyopathy', 'Diarrhoea', 'Dizziness', 'Drug abuse', 'Electrocardiogram QRS complex prolonged', 'Electrocardiogram QT prolonged', 'Electrocardiogram T wave alternans', 'Hyperhidrosis', 'Hypokalaemia', 'Long QT syndrome', 'Overdose', 'Renal impairment', 'Substance abuse', 'Substance use', 'Syncope', 'Torsade de pointes', 'Ventricular arrhythmia', 'Ventricular tachycardia'], type: <class 'list'>

In [91]:
metrics_df.mean()

rank_precision@5      0.302519
rank-precision@10     0.335506
rank-precision@25     0.476046
recall@5              0.243553
recall@10             0.266467
recall@20             0.293134
recall@50             0.295293
recall@100            0.295293
recall@200            0.295293
recall@300            0.295293
recall@400            0.295293
recall@500            0.295293
precision@5           0.174593
precision@10          0.115601
num_ids              19.435556
dtype: float64

In [81]:
norank_metrics = compute_metrics(top_answer_df, gt_col_name="reactions_list", pred_col_name="pred_reaction_norank")

gt_ids: ['Facial paralysis', 'Methaemoglobinaemia'], type: <class 'list'>
ids: ['Cyanosis', 'Methaemoglobinaemia', 'Cyanosis central', 'Cyanopsia', 'Dysglobulinaemia', 'Congenital methaemoglobinaemia', 'Hypoxia', 'Hypochromasia'], type: <class 'list'>
gt_ids: ['Haemoglobin decreased', 'Off label use', 'Retroperitoneal haemorrhage'], type: <class 'list'>
ids: ['Autoimmune haemolytic anaemia', 'Autoimmune anaemia', 'Renal failure', 'Autoimmune pancytopenia', 'Thrombocytopenia', 'Haemolytic anaemia', 'Renal haemorrhage', 'Platelet dysfunction', 'Renal impairment'], type: <class 'list'>
gt_ids: ['Cholecystitis acute', 'Haemobilia', 'Haemorrhagic ascites', 'Haemorrhagic cholecystitis'], type: <class 'list'>
ids: ['Haemorrhagic cholecystitis', 'Haemobilia', 'Cystitis haemorrhagic', 'Hepatic haemorrhage', 'Gastrointestinal haemorrhage', 'Haemorrhage', 'Haemorrhagic disorder', 'Intestinal varices haemorrhage', 'Haemorrhoidal haemorrhage', 'Intestinal haemorrhage', 'Haemorrhagic hepatic cyst', 'Upper gastrointestinal haemorrhage', 'Umbilical haemorrhage', 'Gastric varices haemorrhage', 'Gastric haemorrhage', 'Ciliary body haemorrhage', 'Ulcer haemorrhage', 'Internal haemorrhage', 'Gastrointestinal ulcer haemorrhage', 'Haemorrhage urinary tract', 'Urinary bladder haemorrhage', 'Peptic ulcer haemorrhage', 'Gastritis haemorrhagic', 'Genital haemorrhage', 'Gastric ulcer haemorrhage, obstructive', 'Rectal ulcer haemorrhage', 'Haemorrhagic cyst', 'Cholecystitis', 'Enterocolitis haemorrhagic', 'Gastric ulcer haemorrhage', 'Uterine haemorrhage', 'Vaginal haemorrhage', 'Oesophageal varices haemorrhage', 'Wound haemorrhage', 'Pancreatitis haemorrhagic', 'Pelvic haemorrhage', 'Pharyngeal haemorrhage', 'Gastroduodenal haemorrhage', 'Choroidal haemorrhage', 'Haemorrhagic fever', 'Rectal haemorrhage', 'Diarrhoea haemorrhagic', 'Haemorrhagic erosive gastritis', 'Foetal-maternal haemorrhage', 'Gastrointestinal vascular malformation haemorrhagic', 'Oesophageal ulcer haemorrhage', 'Haemorrhage foetal', 'Large intestinal haemorrhage', 'Viral haemorrhagic cystitis', 'Ureteric haemorrhage', 'Urethral haemorrhage', 'Haemorrhagic vasculitis', 'Haemorrhagic breast cyst', 'Mucosal haemorrhage', 'Oesophageal haemorrhage', 'Gastritis alcoholic haemorrhagic', 'Duodenal ulcer haemorrhage', 'Bronchial varices haemorrhage', 'Anorectal varices haemorrhage', 'Umbilical cord haemorrhage', 'Cervix haemorrhage uterine', 'Diverticulitis intestinal haemorrhagic', 'Proctitis haemorrhagic', 'Ischaemic cholecystitis', 'Shock haemorrhagic', 'Haemorrhage in pregnancy', 'Traumatic haemorrhage', 'Urogenital haemorrhage', 'Vulval haemorrhage', 'Haematochezia', 'Duodenitis haemorrhagic', 'Haemorrhagic thyroid cyst', 'Mesenteric haemorrhage', 'Breast haemorrhage', 'Subchorionic haemorrhage', 'Pancreatic haemorrhage', 'Arterial haemorrhage', 'Bronchial haemorrhage', 'Haemorrhagic ovarian cyst', 'Haemorrhagic stroke', 'Haemorrhagic ascites', 'Respiratory tract haemorrhage', 'Oesophagitis haemorrhagic', 'Abdominal wall haemorrhage', 'Haemorrhagic varicella syndrome', 'Large intestinal ulcer haemorrhage', 'Anal haemorrhage', 'Lower gastrointestinal haemorrhage', 'Haemorrhagic infarction', 'Haemorrhage neonatal', 'Anal ulcer haemorrhage', 'Vitreous haemorrhage', 'Haemorrhagic urticaria', 'Haemorrhage coronary artery', 'Venous haemorrhage', 'Graft haemorrhage', 'Intra-abdominal haemorrhage', 'Cholecystocholangitis', 'Mucocutaneous haemorrhage', 'Chronic gastrointestinal bleeding', 'Skin haemorrhage', 'Cholelithiasis', 'Spontaneous haemorrhage', 'Cholecystitis acute', 'Haematoma', 'Eye haemorrhage', 'Retinopathy haemorrhagic', 'Hepatobiliary infection', 'Injection site haemorrhage', 'Muscle haemorrhage', 'Vascular graft haemorrhage', 'Cholangitis', 'Haemorrhage subepidermal', 'Blood bilirubin', 'Soft tissue haemorrhage', 'Wound haematoma', 'Vaccination site haemorrhage', 'Puncture site haemorrhage', 'Biliary-vascular fistula', 'Administration site haemorrhage', 'Gallbladder oedema', 'Biliary tract infection', 'Haemorrhage prophylaxis', 'Procedural haemorrhage', 'Hepatobiliary disease', 'Biliary sepsis', 'Gallbladder injury', 'Lip haemorrhage', 'Haemostasis', 'Vessel puncture site haemorrhage', 'Cholestatic liver injury', 'Post procedural haemorrhage', 'Biliary tract disorder', 'Naevus haemorrhage', 'Medical device site haemorrhage', 'Gallbladder disorder', 'Vascular access site haemorrhage', 'Biliary ischaemia', 'Extra-axial haemorrhage'], type: <class 'list'>
gt_ids: ['Decreased appetite', 'Disease progression', 'Dyspnoea', 'Fatigue'], type: <class 'list'>
ids: ['Transaminases abnormal', 'Hypertransaminasaemia', 'Gastrointestinal mucosa hyperaemia'], type: <class 'list'>
gt_ids: ['Bronchopulmonary aspergillosis', 'Obliterative bronchiolitis', 'Off label use', 'Respiratory failure'], type: <class 'list'>
ids: ['Bronchopulmonary aspergillosis', 'Obliterative bronchiolitis', 'Bronchiolitis', 'Bronchitis fungal', 'Necrotising bronchiolitis', 'Pulmonary mycosis', 'Bronchopulmonary aspergillosis allergic', 'Actinomycotic pulmonary infection', 'Allergic bronchopulmonary mycosis', 'Aspergillus infection', 'Pulmonary sporotrichosis', 'Pulmonary vasculitis', 'Respiratory tract infection fungal', 'Aspergilloma', 'Bronchitis mycoplasmal', 'Pulmonary mucormycosis', 'Bronchitis pneumococcal', 'Pneumonia toxoplasmal', 'Sinusitis aspergillus', 'Acute pulmonary histoplasmosis', 'Meningitis aspergillus', 'Upper respiratory fungal infection', 'Oro-pharyngeal aspergillosis', 'Pulmonary granuloma', 'Alveolitis', 'Pneumonia fungal', 'Pulmonary veno-occlusive disease', 'Bronchitis bacterial', 'Bronchitis', 'Lower respiratory tract infection fungal', 'Fungal tracheitis', 'Allergic bronchitis', 'Lung abscess', 'Pneumonitis', 'Cerebral aspergillosis', 'Bronchial ulceration', 'Eosinophilic bronchitis', 'Pulmonary lymphangiectasia', 'Bronchostenosis', 'Alveolar lung disease', 'Candida pneumonia', 'Systemic sclerosis pulmonary', 'Disseminated aspergillosis', 'Aspergillosis oral', 'Bronchopulmonary disease', 'Lung disorder', 'Acquired bronchial cyst', 'Pulmonary sepsis', 'Bronchial obstruction', 'Bronchiectasis', 'Fibrinous bronchitis', 'Acute interstitial pneumonitis', 'Pulmonary fibrosis', 'Pulmonary mass', 'Pulmonary arteriopathy', 'Obstructive airways disorder', 'Respiratory disorder', 'Bronchomalacia', 'Granulomatous pneumonitis', 'Bronchial disorder', 'Bronchitis haemophilus', 'Noninfective bronchitis', 'Combined pulmonary fibrosis and emphysema', 'Pulmonary necrosis', 'Bronchial oedema', 'Restrictive pulmonary disease', 'Lung diffusion disorder', 'Pseudomonas bronchitis', 'Respiratory fume inhalation disorder', 'Pulmonary malformation', 'Pneumonia aspiration', 'Pulmonary pneumatocele', 'Pulmonary infarction', 'Bronchial neoplasm', 'Lung neoplasm', 'Alveolitis necrotising', 'Respiratory tract ulceration', 'Pneumonia', 'Bronchial haemorrhage', 'Respiratory tract infection', 'Pulmonary capillary haemangiomatosis', 'Pneumonia escherichia', 'Aspergillus test', 'Infective exacerbation of bronchiectasis', 'Pulmonary renal syndrome', 'Fungal pharyngitis', 'Fungal infection', 'Pulmonary artery occlusion', 'Respiratory tract neoplasm', 'Interstitial lung disease', 'Pulmonary vascular disorder', 'Leukaemic infiltration pulmonary', 'Nasal candidiasis'], type: <class 'list'>
gt_ids: ['Neurotoxicity', 'Overdose', 'Paralysis'], type: <class 'list'>
ids: ['Neurotoxicity', 'Sensory disturbance', 'Paralysis'], type: <class 'list'>
gt_ids: ['Bradycardia', 'Brugada syndrome', 'Drug ineffective', 'Electrocardiogram abnormal', 'Unmasking of previously unidentified disease'], type: <class 'list'>
ids: ['Ventricular arrhythmia', 'Electrocardiogram QT prolonged', 'Syncope', 'Ventricular tachyarrhythmia', 'Bradyarrhythmia', 'Paroxysmal arrhythmia', 'Arrhythmia', 'Electrocardiogram QT interval abnormal', 'Sinus bradycardia', 'Ventricular tachycardia', 'Electrocardiogram QT interval', 'Bradycardia', 'Long QT syndrome', 'Electrocardiogram RR interval prolonged', 'Withdrawal arrhythmia'], type: <class 'list'>
gt_ids: ['Dysarthria', 'Hemiparesis'], type: <class 'list'>
ids: ['Dysarthria', 'Hypokinetic dysarthria', 'Hemiparesis', 'Ischaemic stroke', 'Cerebral thrombosis', 'Thrombotic stroke', 'Precerebral artery thrombosis', 'Hemiplegia', 'Ischaemic cerebral infarction', 'Cerebral artery thrombosis', 'Hemiataxia', 'Vertebrobasilar stroke'], type: <class 'list'>
gt_ids: ['Condition aggravated'], type: <class 'list'>
ids: ['Amenorrhoea-galactorrhoea syndrome', 'Amenorrhoea', 'Galactorrhoea', 'Pituitary amenorrhoea', 'Hypomenorrhoea', 'Amniorrhoea', 'Oligomenorrhoea', 'Galactocele', 'Menstrual disorder', 'Blood gonadotrophin', 'Ovarian disorder', 'Female reproductive tract disorder', 'Galactosaemia', 'Galactostasis', 'Blood gonadotrophin abnormal'], type: <class 'list'>
gt_ids: ['Condition aggravated', 'Dyspnoea', 'Gastrooesophageal reflux disease', 'Product use in unapproved indication', 'Pulmonary oedema'], type: <class 'list'>
ids: ['Pulmonary oedema', 'Respiratory tract oedema', 'Gastrointestinal oedema', 'Acute pulmonary oedema', 'Pulmonary oedema neonatal', 'Oesophageal oedema', 'Reexpansion pulmonary oedema', 'Bronchial oedema', 'Pulmonary oedema post fume inhalation', 'Respiratory symptom', 'Negative pressure pulmonary oedema', 'Pharyngeal oedema', 'Allergic respiratory symptom', 'Pulmonary pain', 'Non-cardiogenic pulmonary oedema', 'Visceral oedema', 'Gastric pneumatosis', 'Gestational oedema', 'Laryngotracheal oedema', 'Pulmonary mass', 'Tracheal oedema', 'Oedema mucosal', 'Nasal oedema', 'Reflux gastritis', 'Laryngeal oedema', 'Allergic oedema', 'Oedema due to cardiac disease', 'Gastrooesophageal reflux disease', 'Oropharyngeal oedema', 'Breast oedema', 'Pulmonary hypertension', 'Pulmonary congestion', 'Circumoral oedema', 'Tongue oedema', 'Generalised oedema', 'Muscle oedema', 'Duodenogastric reflux', 'Gastric ulcer, obstructive', 'Myocardial oedema', 'Periportal oedema', 'Oesophageal spasm', 'Oesophageal fibrosis', 'Oesophageal discomfort', 'Medical device site oedema', 'Injection site oedema', 'Abdominal wall oedema', 'Gastric ulcer haemorrhage, obstructive', 'Gravitational oedema', 'Respiratory disorder', 'Pulmonary vascular disorder', 'Nipple oedema', 'Oesophageal pain', 'Abdominal symptom', 'Face oedema', 'Oesophageal obstruction', 'Respiratory failure', 'Perinephric oedema', 'Pulmonary physical examination abnormal', 'Stoma site oedema', 'Eye oedema', 'Angiogram pulmonary abnormal', 'Gastric fibrosis', 'Peritumoural oedema', 'Gastric mucosa erythema', 'Obstruction gastric', 'Chest discomfort', 'Cardiovascular symptom', 'Respiratory tract irritation', 'Oesophageal ulcer', 'Oedema', 'Dyspnoea exertional', 'Infusion site oedema', 'Oesophageal disorder', 'Localised oedema', 'Pulmonary physical examination', 'Skin oedema', 'Retinal oedema', 'Oesophageal mucosa erythema', 'Respiratory acidosis', 'Angiogram pulmonary', 'Heat oedema', 'Periorbital oedema', 'Pulmonary arterial pressure', 'Oesophagitis', 'Oesophageal irritation', 'Oesophageal motility test', 'Gastric haemorrhage', 'Gastric disorder', 'Pulmonary artery occlusion', 'Retroperitoneal oedema', 'Conjunctival oedema', 'Pulmonary arterial pressure abnormal', 'Dyskinesia oesophageal', 'Vaginal oedema', 'Impaired gastric emptying', 'Oesophageal ulcer haemorrhage'], type: <class 'list'>
gt_ids: ['Drug ineffective', 'Off label use'], type: <class 'list'>
ids: ['Hallucination, auditory', 'Hallucination, gustatory', 'Hallucination, olfactory', 'Suicidal behaviour', 'Suicidal ideation', 'Hallucinations, mixed', 'Hallucination, synaesthetic', 'Depression suicidal', 'Psychiatric symptom', 'Psychotic symptom', 'Neuropsychiatric symptoms', 'Hallucination, tactile', 'Hallucination', 'Psychotic disorder', 'Hallucinations mixed', 'Psychotic behaviour', 'Hallucination, visual', 'Schizophrenia', 'Depressive symptom', 'Acute psychosis', 'Hallucination auditory', 'Schizophreniform disorder', 'Schizoaffective disorder', 'Bipolar disorder', 'Hypnagogic hallucination', 'Depersonalisation/derealisation disorder', 'Hysterical psychosis'], type: <class 'list'>
gt_ids: ['Abdominal pain', 'Alopecia', 'Anaemia', 'Blood albumin decreased', 'Colorectal adenocarcinoma', 'Death', 'Deep vein thrombosis', 'Drug ineffective', 'Leukopenia', 'Lymphopenia', 'Neuropathy peripheral', 'Neutropenia', 'Sepsis'], type: <class 'list'>
ids: ['Lymphopenia', 'Leukopenia', 'Erythropenia', 'Radiation leukopenia', 'Lymphocytopenia neonatal', 'Leukopenia neonatal', 'Lymphostasis', 'Enteritis leukopenic', 'Lymphadenopathy', 'Lymphocytic leukaemia', 'Leukoerythroblastic anaemia', 'Lymphoplasia', 'Lymphorrhoea', 'Leukocyturia', 'Leukocytosis', 'White blood cell disorder', 'Leukostasis syndrome', 'Leukaemic lymphoma', 'Lymphocytosis', 'Leukaemia', 'B-lymphocyte abnormalities', 'Lymphoedema', 'Lymphatic disorder', 'Lymphoblastosis', 'Haematotoxicity', 'Blood disorder', 'Immunodeficiency', 'Anaemia', 'Leukaemia monocytic', 'Autoimmune anaemia', 'Lymphatic insufficiency', 'Granulocytopenia', 'Melanaemia', 'Pancytopenia', 'Leukaemia granulocytic', 'Lymphoblast count', 'Microcytic anaemia', 'Lymphocyte count', 'Anaemia macrocytic', 'Blood loss anaemia', 'Bicytopenia', 'Leukoerythroblastosis', 'Neutropenia', 'Bone marrow disorder', 'Haematoma infection', 'Hypothrombinaemia', 'Myelocytosis', 'Haemoglobinaemia', 'Deficiency anaemia', 'Haematopoietic neoplasm', 'Hypoglobulinaemia', 'Anaemia of malignant disease', 'Red blood cell abnormality', 'Immune-mediated cytopenia', 'Anaemia splenic', 'Anaemia prophylaxis', 'Refractory anaemia with an excess of blasts', 'Neutropenic infection', 'Leukaemia basophilic', 'Blood erythropoietin', 'Anaemia megaloblastic', 'Cytopenia', 'Lymphocyte morphology', 'Bone marrow ischaemia', 'Anaemia of chronic disease', 'B-lymphocyte count', 'Bone marrow haemorrhage'], type: <class 'list'>
gt_ids: ['Basal cell carcinoma', 'CD4 lymphocytes decreased', 'Neutropenia', 'Thrombocytopenia', 'Toxicity to various agents'], type: <class 'list'>
ids: ['Febrile neutropenia', 'Neutropenia', 'Transfusion-related alloimmune neutropenia', 'Pseudomonal bacteraemia', 'Neutropenic infection', 'Thrombocytopenia', 'Granulocytopenia', 'Pseudomonal sepsis', 'Pancytopenia'], type: <class 'list'>
gt_ids: ['Tumour lysis syndrome'], type: <class 'list'>
ids: ['Transfusion-related alloimmune neutropenia', 'Infusion related reaction', 'Infusion related hypersensitivity reaction', 'Transfusion-related immunomodulation reaction', 'Neutropenia', 'Transfusion related complication', 'Transfusion reaction', 'Allergic transfusion reaction', 'Anaphylactic transfusion reaction', 'Thrombocytopenia', 'Hypotensive transfusion reaction', 'Haemolytic transfusion reaction', 'Transfusion-related circulatory overload', 'Transfusion-associated dyspnoea', 'Acute haemolytic transfusion reaction', 'Immune thrombocytopenia', 'Pancytopenia', 'Amegakaryocytic thrombocytopenia', 'Granulocytopenia', 'Thrombocytopenic purpura', 'Immune-mediated pancytopenia', 'Neutropenic infection', 'Immune-mediated cytopenia', 'Nephrogenic anaemia', 'Cyclic neutropenia', 'Bicytopenia', 'Infusion site hypersensitivity', 'Blood product transfusion dependent', 'Idiopathic neutropenia', 'Refractory anaemia with an excess of blasts', 'Hypothrombinaemia', 'Haemangioma-thrombocytopenia syndrome', 'Platelet transfusion', 'Injection related reaction', 'Congenital thrombocytopenia', 'Neutropenic sepsis', 'Anaemia', 'Haematotoxicity', 'Cytopenia', 'Non-immune heparin associated thrombocytopenia', 'Transfusion', 'Autoimmune heparin-induced thrombocytopenia', 'Autoimmune pancytopenia'], type: <class 'list'>
gt_ids: ['Acute kidney injury', 'Anaemia', 'Disease progression', 'Haematotoxicity', 'Microangiopathic haemolytic anaemia', 'Mucosal inflammation', 'Neoplasm progression', 'Neutropenia', 'Renal failure', 'Thrombocytopenia', 'Thrombotic microangiopathy'], type: <class 'list'>
ids: ['Thrombotic microangiopathy', 'Microangiopathic haemolytic anaemia', 'Renal-limited thrombotic microangiopathy', 'Pulmonary tumour thrombotic microangiopathy', 'Microangiopathy', 'Haemolytic uraemic syndrome'], type: <class 'list'>
gt_ids: ['Amenorrhoea', 'Device issue', 'Drug ineffective', 'Ectopic pregnancy with contraceptive device', 'Exposure during pregnancy', 'Haemoperitoneum', 'Ruptured ectopic pregnancy'], type: <class 'list'>
ids: ['Ruptured ectopic pregnancy', 'Ectopic pregnancy with contraceptive device', 'Ectopic pregnancy', 'Tubal rupture', 'Uterine rupture', 'Ectopic pregnancy termination', 'Reproductive complication associated with device', 'Ovarian rupture', 'Abortion of ectopic pregnancy', 'Intra-uterine contraceptive device removal', 'Pregnancy with contraceptive device', 'Cyst rupture', 'Intra-uterine contraceptive device insertion', 'Implantation complication', 'Foreign body in reproductive tract', 'Fallopian tube perforation', 'Ectopic pregnancy under hormonal contraception', 'Peripartum haemorrhage', 'Device failure', 'Fallopian tube obstruction'], type: <class 'list'>
gt_ids: ['Atypical haemolytic uraemic syndrome', 'Hepatic haematoma', 'Off label use'], type: <class 'list'>
ids: ['Red blood cell schistocytes', 'Spherocytic anaemia', 'Platelet anisocytosis', 'Red blood cell anisocytes', 'Schistocytosis', 'Anisocytosis', 'Haemolytic anaemia', 'Hyperthrombinaemia'], type: <class 'list'>
gt_ids: ['Gastroenteritis radiation', 'Ileal perforation'], type: <class 'list'>
ids: ['Gastroenteritis radiation', 'Radiation proctitis', 'Radiation mucositis', 'Small intestinal perforation', 'Intestinal perforation', 'Radiation inflammation', 'Gastrointestinal perforation', 'Small intestinal ulcer perforation', 'Radiation associated pain', 'Ileal perforation', 'Enteritis', 'Radiotherapy to gastrointestinal tract', 'Intestinal ulcer perforation', 'Peritonitis', 'Ileal ulcer perforation', 'Radiation vasculitis', 'Radiotherapy to abdomen', 'Appendicitis perforated'], type: <class 'list'>
gt_ids: ['Labelled drug-drug interaction issue', 'Pulmonary alveolar haemorrhage', 'Pulmonary haemorrhage', 'Thrombocytopenia'], type: <class 'list'>
ids: ['Thrombocytopenia', 'Pulmonary alveolar haemorrhage', 'Diffuse alveolar damage', 'Pulmonary haemorrhage', 'Bronchial haemorrhage', 'Thrombocytosis', 'Pulmonary thrombosis', 'Respiratory tract haemorrhage', 'Pulmonary haematoma', 'Alveolar lung disease', 'Thrombocytopenic purpura', 'Haemorrhagic pneumonia', 'Alveolitis', 'Bronchial varices haemorrhage', 'Cytopenia', 'Tracheal haemorrhage', 'Immune thrombocytopenia', 'Pharyngeal haemorrhage', 'Thoracic haemorrhage', 'Haemoptysis', 'Transfusion-associated dyspnoea', 'Pulmonary microemboli', 'Respiratory failure', 'Coagulopathy', 'Mucocutaneous haemorrhage', 'Acute lung injury', 'Pulmonary vascular disorder', 'Upper-airway cough syndrome', 'Acute respiratory failure', 'Respiratory disorder', 'Mouth haemorrhage', 'Pulmonary vasculitis', 'Pulmonary congestion', 'Haemorrhagic disorder', 'Lung disorder'], type: <class 'list'>
gt_ids: ['Lichenoid keratosis', 'Pemphigoid', 'Skin toxicity', 'Tubulointerstitial nephritis'], type: <class 'list'>
ids: ['Tubulointerstitial nephritis', 'Tubulointerstitial nephritis and uveitis syndrome', 'Nephritis', 'Glomerulonephritis acute', 'Nephritic syndrome', 'Acute cutaneous lupus erythematosus', 'Nephritis allergic', 'Lupus nephritis', 'Immunotactoid glomerulonephritis', 'Oedema due to renal disease', 'Autoimmune nephritis', 'Pemphigoid', 'Nephritis bacterial', 'Nephrectasia', 'Pyelonephritis acute', 'Dermatitis bullous', 'Glomerulonephritis', 'Immune-mediated nephritis', 'Oedematous kidney', 'Immune-mediated renal disorder', 'Nephritis haemorrhagic', 'Pemphigus', 'Autoimmune blistering disease', 'Neutrophilic dermatosis', 'Bullous haemorrhagic dermatosis', 'Kidney infection', 'Perinephritis'], type: <class 'list'>
gt_ids: ['Angle closure glaucoma', 'Choroidal effusion'], type: <class 'list'>

In [82]:
norank_metrics.mean()

rank_precision@5      0.239185
rank-precision@10     0.251441
rank-precision@25     0.273030
recall@5              0.212867
recall@10             0.246842
recall@20             0.271991
recall@50             0.284028
recall@100            0.287659
recall@200            0.293215
recall@300            0.293215
recall@400            0.293215
recall@500            0.293215
precision@5           0.157778
precision@10          0.113062
num_ids              25.346667
dtype: float64

# Check the normal output

In [3]:

ref_df = pd.read_csv("biodex_results/JoinCascade/nsamples=250_recall_target=0.7_precision_target=0.7_range=150/res.csv")

In [4]:
ref_df.head(5)

,title,abstract,reactions,reactions_list,pred_reaction
0,A Case Report of Acute Transient Encephalopath...,Methemoglobinemia is caused due to an increase...,"Facial paralysis, Methaemoglobinaemia","['Facial paralysis', 'Methaemoglobinaemia']","['Cyanosis', 'Methaemoglobinaemia', 'Cyanosis ..."
1,A Case Report of COVID-Associated Catastrophic...,Antiphospholipid syndrome (APS) is an autoimmu...,"Haemoglobin decreased, Off label use, Retroper...","['Haemoglobin decreased', 'Off label use', 'Re...","['Autoimmune haemolytic anaemia', 'Autoimmune ..."
2,A Case of Hemorrhagic Cholecystitis and Hemobi...,BACKGROUND Hemorrhagic cholecystitis is a rare...,"Cholecystitis acute, Haemobilia, Haemorrhagic ...","['Cholecystitis acute', 'Haemobilia', 'Haemorr...","['Haemorrhagic cholecystitis', 'Haemobilia', '..."
3,A Case of Non-small Cell Lung Cancer Treated w...,The echinoderm microtubule associated protein-...,"Decreased appetite, Disease progression, Dyspn...","['Decreased appetite', 'Disease progression', ...","['Transaminases abnormal', 'Hypertransaminasae..."
4,A Case of Paraneoplastic Pemphigus as a Preced...,"Paraneoplastic pemphigus is a rare, life-threa...","Bronchopulmonary aspergillosis, Obliterative b...","['Bronchopulmonary aspergillosis', 'Obliterati...","['Bronchopulmonary aspergillosis', 'Obliterati..."

In [5]:
ref_metrics = compute_metrics(ref_df)
ref_metrics.mean()

gt_ids: ['Facial paralysis', 'Methaemoglobinaemia'], type: <class 'str'>
ids: ['Cyanosis', 'Methaemoglobinaemia', 'Cyanosis central', 'Cyanopsia', 'Dysglobulinaemia', 'Congenital methaemoglobinaemia', 'Hypoxia', 'Hypochromasia'], type: <class 'str'>
gt_ids: ['Haemoglobin decreased', 'Off label use', 'Retroperitoneal haemorrhage'], type: <class 'str'>
ids: ['Autoimmune haemolytic anaemia', 'Autoimmune anaemia', 'Renal failure', 'Autoimmune pancytopenia', 'Thrombocytopenia', 'Haemolytic anaemia', 'Renal haemorrhage', 'Platelet dysfunction', 'Renal impairment'], type: <class 'str'>
gt_ids: ['Cholecystitis acute', 'Haemobilia', 'Haemorrhagic ascites', 'Haemorrhagic cholecystitis'], type: <class 'str'>
ids: ['Haemorrhagic cholecystitis', 'Haemobilia', 'Cystitis haemorrhagic', 'Hepatic haemorrhage', 'Gastrointestinal haemorrhage', 'Haemorrhage', 'Haemorrhagic disorder', 'Intestinal varices haemorrhage', 'Haemorrhoidal haemorrhage', 'Intestinal haemorrhage', 'Haemorrhagic hepatic cyst', 'Upper gastrointestinal haemorrhage', 'Umbilical haemorrhage', 'Gastric varices haemorrhage', 'Gastric haemorrhage', 'Ciliary body haemorrhage', 'Ulcer haemorrhage', 'Internal haemorrhage', 'Gastrointestinal ulcer haemorrhage', 'Haemorrhage urinary tract', 'Urinary bladder haemorrhage', 'Peptic ulcer haemorrhage', 'Gastritis haemorrhagic', 'Genital haemorrhage', 'Gastric ulcer haemorrhage, obstructive', 'Rectal ulcer haemorrhage', 'Haemorrhagic cyst', 'Cholecystitis', 'Enterocolitis haemorrhagic', 'Gastric ulcer haemorrhage', 'Uterine haemorrhage', 'Vaginal haemorrhage', 'Oesophageal varices haemorrhage', 'Wound haemorrhage', 'Pancreatitis haemorrhagic', 'Pelvic haemorrhage', 'Pharyngeal haemorrhage', 'Gastroduodenal haemorrhage', 'Choroidal haemorrhage', 'Haemorrhagic fever', 'Rectal haemorrhage', 'Diarrhoea haemorrhagic', 'Haemorrhagic erosive gastritis', 'Foetal-maternal haemorrhage', 'Gastrointestinal vascular malformation haemorrhagic', 'Oesophageal ulcer haemorrhage', 'Haemorrhage foetal', 'Large intestinal haemorrhage', 'Viral haemorrhagic cystitis', 'Ureteric haemorrhage', 'Urethral haemorrhage', 'Haemorrhagic vasculitis', 'Haemorrhagic breast cyst', 'Mucosal haemorrhage', 'Oesophageal haemorrhage', 'Gastritis alcoholic haemorrhagic', 'Duodenal ulcer haemorrhage', 'Bronchial varices haemorrhage', 'Anorectal varices haemorrhage', 'Umbilical cord haemorrhage', 'Cervix haemorrhage uterine', 'Diverticulitis intestinal haemorrhagic', 'Proctitis haemorrhagic', 'Ischaemic cholecystitis', 'Shock haemorrhagic', 'Haemorrhage in pregnancy', 'Traumatic haemorrhage', 'Urogenital haemorrhage', 'Vulval haemorrhage', 'Haematochezia', 'Duodenitis haemorrhagic', 'Haemorrhagic thyroid cyst', 'Mesenteric haemorrhage', 'Breast haemorrhage', 'Subchorionic haemorrhage', 'Pancreatic haemorrhage', 'Arterial haemorrhage', 'Bronchial haemorrhage', 'Haemorrhagic ovarian cyst', 'Haemorrhagic stroke', 'Haemorrhagic ascites', 'Respiratory tract haemorrhage', 'Oesophagitis haemorrhagic', 'Abdominal wall haemorrhage', 'Haemorrhagic varicella syndrome', 'Large intestinal ulcer haemorrhage', 'Anal haemorrhage', 'Lower gastrointestinal haemorrhage', 'Haemorrhagic infarction', 'Haemorrhage neonatal', 'Anal ulcer haemorrhage', 'Vitreous haemorrhage', 'Haemorrhagic urticaria', 'Haemorrhage coronary artery', 'Venous haemorrhage', 'Graft haemorrhage', 'Intra-abdominal haemorrhage', 'Cholecystocholangitis', 'Mucocutaneous haemorrhage', 'Chronic gastrointestinal bleeding', 'Skin haemorrhage', 'Cholelithiasis', 'Spontaneous haemorrhage', 'Cholecystitis acute', 'Haematoma', 'Eye haemorrhage', 'Retinopathy haemorrhagic', 'Hepatobiliary infection', 'Injection site haemorrhage', 'Muscle haemorrhage', 'Vascular graft haemorrhage', 'Cholangitis', 'Haemorrhage subepidermal', 'Blood bilirubin', 'Soft tissue haemorrhage', 'Wound haematoma', 'Vaccination site haemorrhage', 'Puncture site haemorrhage', 'Biliary-vascular fistula', 'Administration site haemorrhage', 'Gallbladder oedema', 'Biliary tract infection', 'Haemorrhage prophylaxis', 'Procedural haemorrhage', 'Hepatobiliary disease', 'Biliary sepsis', 'Gallbladder injury', 'Lip haemorrhage', 'Haemostasis', 'Vessel puncture site haemorrhage', 'Cholestatic liver injury', 'Post procedural haemorrhage', 'Biliary tract disorder', 'Naevus haemorrhage', 'Medical device site haemorrhage', 'Gallbladder disorder', 'Vascular access site haemorrhage', 'Biliary ischaemia', 'Extra-axial haemorrhage'], type: <class 'str'>
gt_ids: ['Decreased appetite', 'Disease progression', 'Dyspnoea', 'Fatigue'], type: <class 'str'>
ids: ['Transaminases abnormal', 'Hypertransaminasaemia', 'Gastrointestinal mucosa hyperaemia'], type: <class 'str'>
gt_ids: ['Bronchopulmonary aspergillosis', 'Obliterative bronchiolitis', 'Off label use', 'Respiratory failure'], type: <class 'str'>
ids: ['Bronchopulmonary aspergillosis', 'Obliterative bronchiolitis', 'Bronchiolitis', 'Bronchitis fungal', 'Necrotising bronchiolitis', 'Pulmonary mycosis', 'Bronchopulmonary aspergillosis allergic', 'Actinomycotic pulmonary infection', 'Allergic bronchopulmonary mycosis', 'Aspergillus infection', 'Pulmonary sporotrichosis', 'Pulmonary vasculitis', 'Respiratory tract infection fungal', 'Aspergilloma', 'Bronchitis mycoplasmal', 'Pulmonary mucormycosis', 'Bronchitis pneumococcal', 'Pneumonia toxoplasmal', 'Sinusitis aspergillus', 'Acute pulmonary histoplasmosis', 'Meningitis aspergillus', 'Upper respiratory fungal infection', 'Oro-pharyngeal aspergillosis', 'Pulmonary granuloma', 'Alveolitis', 'Pneumonia fungal', 'Pulmonary veno-occlusive disease', 'Bronchitis bacterial', 'Bronchitis', 'Lower respiratory tract infection fungal', 'Fungal tracheitis', 'Allergic bronchitis', 'Lung abscess', 'Pneumonitis', 'Cerebral aspergillosis', 'Bronchial ulceration', 'Eosinophilic bronchitis', 'Pulmonary lymphangiectasia', 'Bronchostenosis', 'Alveolar lung disease', 'Candida pneumonia', 'Systemic sclerosis pulmonary', 'Disseminated aspergillosis', 'Aspergillosis oral', 'Bronchopulmonary disease', 'Lung disorder', 'Acquired bronchial cyst', 'Pulmonary sepsis', 'Bronchial obstruction', 'Bronchiectasis', 'Fibrinous bronchitis', 'Acute interstitial pneumonitis', 'Pulmonary fibrosis', 'Pulmonary mass', 'Pulmonary arteriopathy', 'Obstructive airways disorder', 'Respiratory disorder', 'Bronchomalacia', 'Granulomatous pneumonitis', 'Bronchial disorder', 'Bronchitis haemophilus', 'Noninfective bronchitis', 'Combined pulmonary fibrosis and emphysema', 'Pulmonary necrosis', 'Bronchial oedema', 'Restrictive pulmonary disease', 'Lung diffusion disorder', 'Pseudomonas bronchitis', 'Respiratory fume inhalation disorder', 'Pulmonary malformation', 'Pneumonia aspiration', 'Pulmonary pneumatocele', 'Pulmonary infarction', 'Bronchial neoplasm', 'Lung neoplasm', 'Alveolitis necrotising', 'Respiratory tract ulceration', 'Pneumonia', 'Bronchial haemorrhage', 'Respiratory tract infection', 'Pulmonary capillary haemangiomatosis', 'Pneumonia escherichia', 'Aspergillus test', 'Infective exacerbation of bronchiectasis', 'Pulmonary renal syndrome', 'Fungal pharyngitis', 'Fungal infection', 'Pulmonary artery occlusion', 'Respiratory tract neoplasm', 'Interstitial lung disease', 'Pulmonary vascular disorder', 'Leukaemic infiltration pulmonary', 'Nasal candidiasis'], type: <class 'str'>
gt_ids: ['Neurotoxicity', 'Overdose', 'Paralysis'], type: <class 'str'>
ids: ['Neurotoxicity', 'Sensory disturbance', 'Paralysis'], type: <class 'str'>
gt_ids: ['Bradycardia', 'Brugada syndrome', 'Drug ineffective', 'Electrocardiogram abnormal', 'Unmasking of previously unidentified disease'], type: <class 'str'>
ids: ['Ventricular arrhythmia', 'Electrocardiogram QT prolonged', 'Syncope', 'Ventricular tachyarrhythmia', 'Bradyarrhythmia', 'Paroxysmal arrhythmia', 'Arrhythmia', 'Electrocardiogram QT interval abnormal', 'Sinus bradycardia', 'Ventricular tachycardia', 'Electrocardiogram QT interval', 'Bradycardia', 'Long QT syndrome', 'Electrocardiogram RR interval prolonged', 'Withdrawal arrhythmia'], type: <class 'str'>
gt_ids: ['Dysarthria', 'Hemiparesis'], type: <class 'str'>
ids: ['Dysarthria', 'Hypokinetic dysarthria', 'Hemiparesis', 'Ischaemic stroke', 'Cerebral thrombosis', 'Thrombotic stroke', 'Precerebral artery thrombosis', 'Hemiplegia', 'Ischaemic cerebral infarction', 'Cerebral artery thrombosis', 'Hemiataxia', 'Vertebrobasilar stroke'], type: <class 'str'>
gt_ids: ['Condition aggravated'], type: <class 'str'>
ids: ['Amenorrhoea-galactorrhoea syndrome', 'Amenorrhoea', 'Galactorrhoea', 'Pituitary amenorrhoea', 'Hypomenorrhoea', 'Amniorrhoea', 'Oligomenorrhoea', 'Galactocele', 'Menstrual disorder', 'Blood gonadotrophin', 'Ovarian disorder', 'Female reproductive tract disorder', 'Galactosaemia', 'Galactostasis', 'Blood gonadotrophin abnormal'], type: <class 'str'>
gt_ids: ['Condition aggravated', 'Dyspnoea', 'Gastrooesophageal reflux disease', 'Product use in unapproved indication', 'Pulmonary oedema'], type: <class 'str'>
ids: ['Pulmonary oedema', 'Respiratory tract oedema', 'Gastrointestinal oedema', 'Acute pulmonary oedema', 'Pulmonary oedema neonatal', 'Oesophageal oedema', 'Reexpansion pulmonary oedema', 'Bronchial oedema', 'Pulmonary oedema post fume inhalation', 'Respiratory symptom', 'Negative pressure pulmonary oedema', 'Pharyngeal oedema', 'Allergic respiratory symptom', 'Pulmonary pain', 'Non-cardiogenic pulmonary oedema', 'Visceral oedema', 'Gastric pneumatosis', 'Gestational oedema', 'Laryngotracheal oedema', 'Pulmonary mass', 'Tracheal oedema', 'Oedema mucosal', 'Nasal oedema', 'Reflux gastritis', 'Laryngeal oedema', 'Allergic oedema', 'Oedema due to cardiac disease', 'Gastrooesophageal reflux disease', 'Oropharyngeal oedema', 'Breast oedema', 'Pulmonary hypertension', 'Pulmonary congestion', 'Circumoral oedema', 'Tongue oedema', 'Generalised oedema', 'Muscle oedema', 'Duodenogastric reflux', 'Gastric ulcer, obstructive', 'Myocardial oedema', 'Periportal oedema', 'Oesophageal spasm', 'Oesophageal fibrosis', 'Oesophageal discomfort', 'Medical device site oedema', 'Injection site oedema', 'Abdominal wall oedema', 'Gastric ulcer haemorrhage, obstructive', 'Gravitational oedema', 'Respiratory disorder', 'Pulmonary vascular disorder', 'Nipple oedema', 'Oesophageal pain', 'Abdominal symptom', 'Face oedema', 'Oesophageal obstruction', 'Respiratory failure', 'Perinephric oedema', 'Pulmonary physical examination abnormal', 'Stoma site oedema', 'Eye oedema', 'Angiogram pulmonary abnormal', 'Gastric fibrosis', 'Peritumoural oedema', 'Gastric mucosa erythema', 'Obstruction gastric', 'Chest discomfort', 'Cardiovascular symptom', 'Respiratory tract irritation', 'Oesophageal ulcer', 'Oedema', 'Dyspnoea exertional', 'Infusion site oedema', 'Oesophageal disorder', 'Localised oedema', 'Pulmonary physical examination', 'Skin oedema', 'Retinal oedema', 'Oesophageal mucosa erythema', 'Respiratory acidosis', 'Angiogram pulmonary', 'Heat oedema', 'Periorbital oedema', 'Pulmonary arterial pressure', 'Oesophagitis', 'Oesophageal irritation', 'Oesophageal motility test', 'Gastric haemorrhage', 'Gastric disorder', 'Pulmonary artery occlusion', 'Retroperitoneal oedema', 'Conjunctival oedema', 'Pulmonary arterial pressure abnormal', 'Dyskinesia oesophageal', 'Vaginal oedema', 'Impaired gastric emptying', 'Oesophageal ulcer haemorrhage'], type: <class 'str'>
gt_ids: ['Drug ineffective', 'Off label use'], type: <class 'str'>
ids: ['Hallucination, auditory', 'Hallucination, gustatory', 'Hallucination, olfactory', 'Suicidal behaviour', 'Suicidal ideation', 'Hallucinations, mixed', 'Hallucination, synaesthetic', 'Depression suicidal', 'Psychiatric symptom', 'Psychotic symptom', 'Neuropsychiatric symptoms', 'Hallucination, tactile', 'Hallucination', 'Psychotic disorder', 'Hallucinations mixed', 'Psychotic behaviour', 'Hallucination, visual', 'Schizophrenia', 'Depressive symptom', 'Acute psychosis', 'Hallucination auditory', 'Schizophreniform disorder', 'Schizoaffective disorder', 'Bipolar disorder', 'Hypnagogic hallucination', 'Depersonalisation/derealisation disorder', 'Hysterical psychosis'], type: <class 'str'>
gt_ids: ['Abdominal pain', 'Alopecia', 'Anaemia', 'Blood albumin decreased', 'Colorectal adenocarcinoma', 'Death', 'Deep vein thrombosis', 'Drug ineffective', 'Leukopenia', 'Lymphopenia', 'Neuropathy peripheral', 'Neutropenia', 'Sepsis'], type: <class 'str'>
ids: ['Lymphopenia', 'Leukopenia', 'Erythropenia', 'Radiation leukopenia', 'Lymphocytopenia neonatal', 'Leukopenia neonatal', 'Lymphostasis', 'Enteritis leukopenic', 'Lymphadenopathy', 'Lymphocytic leukaemia', 'Leukoerythroblastic anaemia', 'Lymphoplasia', 'Lymphorrhoea', 'Leukocyturia', 'Leukocytosis', 'White blood cell disorder', 'Leukostasis syndrome', 'Leukaemic lymphoma', 'Lymphocytosis', 'Leukaemia', 'B-lymphocyte abnormalities', 'Lymphoedema', 'Lymphatic disorder', 'Lymphoblastosis', 'Haematotoxicity', 'Blood disorder', 'Immunodeficiency', 'Anaemia', 'Leukaemia monocytic', 'Autoimmune anaemia', 'Lymphatic insufficiency', 'Granulocytopenia', 'Melanaemia', 'Pancytopenia', 'Leukaemia granulocytic', 'Lymphoblast count', 'Microcytic anaemia', 'Lymphocyte count', 'Anaemia macrocytic', 'Blood loss anaemia', 'Bicytopenia', 'Leukoerythroblastosis', 'Neutropenia', 'Bone marrow disorder', 'Haematoma infection', 'Hypothrombinaemia', 'Myelocytosis', 'Haemoglobinaemia', 'Deficiency anaemia', 'Haematopoietic neoplasm', 'Hypoglobulinaemia', 'Anaemia of malignant disease', 'Red blood cell abnormality', 'Immune-mediated cytopenia', 'Anaemia splenic', 'Anaemia prophylaxis', 'Refractory anaemia with an excess of blasts', 'Neutropenic infection', 'Leukaemia basophilic', 'Blood erythropoietin', 'Anaemia megaloblastic', 'Cytopenia', 'Lymphocyte morphology', 'Bone marrow ischaemia', 'Anaemia of chronic disease', 'B-lymphocyte count', 'Bone marrow haemorrhage'], type: <class 'str'>
gt_ids: ['Basal cell carcinoma', 'CD4 lymphocytes decreased', 'Neutropenia', 'Thrombocytopenia', 'Toxicity to various agents'], type: <class 'str'>
ids: ['Febrile neutropenia', 'Neutropenia', 'Transfusion-related alloimmune neutropenia', 'Pseudomonal bacteraemia', 'Neutropenic infection', 'Thrombocytopenia', 'Granulocytopenia', 'Pseudomonal sepsis', 'Pancytopenia'], type: <class 'str'>
gt_ids: ['Tumour lysis syndrome'], type: <class 'str'>
ids: ['Transfusion-related alloimmune neutropenia', 'Infusion related reaction', 'Infusion related hypersensitivity reaction', 'Transfusion-related immunomodulation reaction', 'Neutropenia', 'Transfusion related complication', 'Transfusion reaction', 'Allergic transfusion reaction', 'Anaphylactic transfusion reaction', 'Thrombocytopenia', 'Hypotensive transfusion reaction', 'Haemolytic transfusion reaction', 'Transfusion-related circulatory overload', 'Transfusion-associated dyspnoea', 'Acute haemolytic transfusion reaction', 'Immune thrombocytopenia', 'Pancytopenia', 'Amegakaryocytic thrombocytopenia', 'Granulocytopenia', 'Thrombocytopenic purpura', 'Immune-mediated pancytopenia', 'Neutropenic infection', 'Immune-mediated cytopenia', 'Nephrogenic anaemia', 'Cyclic neutropenia', 'Bicytopenia', 'Infusion site hypersensitivity', 'Blood product transfusion dependent', 'Idiopathic neutropenia', 'Refractory anaemia with an excess of blasts', 'Hypothrombinaemia', 'Haemangioma-thrombocytopenia syndrome', 'Platelet transfusion', 'Injection related reaction', 'Congenital thrombocytopenia', 'Neutropenic sepsis', 'Anaemia', 'Haematotoxicity', 'Cytopenia', 'Non-immune heparin associated thrombocytopenia', 'Transfusion', 'Autoimmune heparin-induced thrombocytopenia', 'Autoimmune pancytopenia'], type: <class 'str'>
gt_ids: ['Acute kidney injury', 'Anaemia', 'Disease progression', 'Haematotoxicity', 'Microangiopathic haemolytic anaemia', 'Mucosal inflammation', 'Neoplasm progression', 'Neutropenia', 'Renal failure', 'Thrombocytopenia', 'Thrombotic microangiopathy'], type: <class 'str'>
ids: ['Thrombotic microangiopathy', 'Microangiopathic haemolytic anaemia', 'Renal-limited thrombotic microangiopathy', 'Pulmonary tumour thrombotic microangiopathy', 'Microangiopathy', 'Haemolytic uraemic syndrome'], type: <class 'str'>
gt_ids: ['Amenorrhoea', 'Device issue', 'Drug ineffective', 'Ectopic pregnancy with contraceptive device', 'Exposure during pregnancy', 'Haemoperitoneum', 'Ruptured ectopic pregnancy'], type: <class 'str'>
ids: ['Ruptured ectopic pregnancy', 'Ectopic pregnancy with contraceptive device', 'Ectopic pregnancy', 'Tubal rupture', 'Uterine rupture', 'Ectopic pregnancy termination', 'Reproductive complication associated with device', 'Ovarian rupture', 'Abortion of ectopic pregnancy', 'Intra-uterine contraceptive device removal', 'Pregnancy with contraceptive device', 'Cyst rupture', 'Intra-uterine contraceptive device insertion', 'Implantation complication', 'Foreign body in reproductive tract', 'Fallopian tube perforation', 'Ectopic pregnancy under hormonal contraception', 'Peripartum haemorrhage', 'Device failure', 'Fallopian tube obstruction'], type: <class 'str'>
gt_ids: ['Atypical haemolytic uraemic syndrome', 'Hepatic haematoma', 'Off label use'], type: <class 'str'>
ids: ['Microangiopathic haemolytic anaemia', 'Haemolytic uraemic syndrome', 'Haemolytic anaemia', 'Hyperkalaemia', 'Thrombotic microangiopathy', 'Hyperthrombinaemia', 'Renal failure', 'Renal vascular thrombosis', 'Autoimmune haemolytic anaemia', 'Renal-limited thrombotic microangiopathy', 'Haemolytic icteroanaemia', 'Atypical haemolytic uraemic syndrome', 'Thrombocytopenia', 'Normocytic anaemia', 'Haemosiderinuria', 'Hyperprothrombinaemia', 'Microangiopathy', 'Haemodialysis', 'Hydraemia', 'Blood urea abnormal', 'Blood urea'], type: <class 'str'>
gt_ids: ['Gastroenteritis radiation', 'Ileal perforation'], type: <class 'str'>
ids: ['Gastroenteritis radiation', 'Radiation proctitis', 'Radiation mucositis', 'Small intestinal perforation', 'Intestinal perforation', 'Radiation inflammation', 'Gastrointestinal perforation', 'Small intestinal ulcer perforation', 'Radiation associated pain', 'Ileal perforation', 'Enteritis', 'Radiotherapy to gastrointestinal tract', 'Intestinal ulcer perforation', 'Peritonitis', 'Ileal ulcer perforation', 'Radiation vasculitis', 'Radiotherapy to abdomen', 'Appendicitis perforated'], type: <class 'str'>
gt_ids: ['Labelled drug-drug interaction issue', 'Pulmonary alveolar haemorrhage', 'Pulmonary haemorrhage', 'Thrombocytopenia'], type: <class 'str'>
ids: ['Thrombocytopenia', 'Pulmonary alveolar haemorrhage', 'Diffuse alveolar damage', 'Pulmonary haemorrhage', 'Bronchial haemorrhage', 'Thrombocytosis', 'Pulmonary thrombosis', 'Respiratory tract haemorrhage', 'Pulmonary haematoma', 'Alveolar lung disease', 'Thrombocytopenic purpura', 'Haemorrhagic pneumonia', 'Alveolitis', 'Bronchial varices haemorrhage', 'Cytopenia', 'Tracheal haemorrhage', 'Immune thrombocytopenia', 'Pharyngeal haemorrhage', 'Thoracic haemorrhage', 'Haemoptysis', 'Transfusion-associated dyspnoea', 'Pulmonary microemboli', 'Respiratory failure', 'Coagulopathy', 'Mucocutaneous haemorrhage', 'Acute lung injury', 'Pulmonary vascular disorder', 'Upper-airway cough syndrome', 'Acute respiratory failure', 'Respiratory disorder', 'Mouth haemorrhage', 'Pulmonary vasculitis', 'Pulmonary congestion', 'Haemorrhagic disorder', 'Lung disorder'], type: <class 'str'>
gt_ids: ['Lichenoid keratosis', 'Pemphigoid', 'Skin toxicity', 'Tubulointerstitial nephritis'], type: <class 'str'>

rank_precision@5       0.860714
rank-precision@10      0.876091
recall@5               0.078515
recall@10              0.142978
recall@20              0.220267
recall@50              0.278794
recall@100             0.304818
recall@200             0.321218
recall@300             0.329600
recall@400             0.334181
recall@500             0.337069
precision@5            0.855357
precision@10           0.798661
num_ids              657.575893
dtype: float64

In [8]:
ref_metrics

,rank_precision@5,rank-precision@10,recall@5,recall@10,recall@20,recall@50,recall@100,recall@200,recall@300,recall@400,recall@500,precision@5,precision@10,num_ids
0,0.8,0.9,0.093023,0.186047,0.325581,0.441860,0.488372,0.511628,0.511628,0.511628,0.511628,0.8,0.8,150
1,0.8,0.9,0.054795,0.095890,0.178082,0.205479,0.260274,0.328767,0.342466,0.342466,0.342466,0.8,0.7,206
2,1.0,1.0,0.054945,0.098901,0.153846,0.219780,0.219780,0.219780,0.219780,0.219780,0.230769,1.0,0.9,3741
3,0.8,0.8,0.058824,0.102941,0.147059,0.205882,0.250000,0.250000,0.250000,0.250000,0.250000,0.8,0.7,89
4,1.0,1.0,0.048077,0.086538,0.144231,0.230769,0.240385,0.240385,0.240385,0.250000,0.250000,1.0,0.9,2457
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219,1.0,1.0,0.087719,0.175439,0.245614,0.298246,0.333333,0.350877,0.403509,0.403509,0.403509,1.0,1.0,655
220,0.6,0.7,0.044776,0.089552,0.149254,0.208955,0.208955,0.208955,0.208955,0.208955,0.208955,0.6,0.6,35
221,1.0,1.0,0.012225,0.022005,0.036675,0.051345,0.053790,0.061125,0.066015,0.066015,0.073350,1.0,0.9,447
222,1.0,1.0,0.079365,0.158730,0.206349,0.253968,0.301587,0.301587,0.301587,0.301587,0.317460,1.0,1.0,950
223,1.0,1.0,0.081967,0.131148,0.180328,0.229508,0.295082,0.344262,0.344262,0.344262,0.344262,1.0,0.8,176

# Map df

In [4]:
map_df = read_csv("map_output.csv")

UnboundLocalError: local variable 'df' referenced before assignment